### ISSUE TITLE
APSN token issue

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#1075]
<img width="304" alt="image" src="https://user-images.githubusercontent.com/11156370/217624350-c644350f-5d04-4c98-847a-6818f992d8c5.png">

**Comment by nicolasburtey** [comment]
issue may be on the firebase end?

https://github.com/invertase/react-native-firebase/issues/6893

**Comment by nicolasburtey** [comment]
doing a full install off the app made the problem go away... closing for now

**Comment by 4sskick** [comment]
> doing a full re-install off the app made the problem go away... closing for now

no fix config for this? I also having this issue
