### ISSUE TITLE
Should languages themselves be translated?

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#1082]

**Comment by pretyflaco** [comment]
I think language names should not be translated, but rather be displayed in native name like in WOS:
![image](https://user-images.githubusercontent.com/32958103/221192827-0ca19b54-f025-4927-a267-0bde31aa18c3.png)

This would solve cases where user accidentally selects a language with non-latin scripture and cannot find their way back to their language (see below)
![image](https://user-images.githubusercontent.com/32958103/221193275-f143bc13-cb63-4c96-a8e2-52c673de3654.png)

**Comment by nicolasburtey** [comment]
Yup I also think this is what make most sense

**Comment by nicolasburtey** [comment]
done
