### ISSUE TITLE
Scanning an expired invoice shows: This is not a valid Bitcoin address or Lightning invoice

### ISSUE THREAD

**Issue by openoms** [GaloyMoney/galoy-mobile#1089]
Scanning an expired invoice shows: This is not a valid Bitcoin address or Lightning invoice while showing the correct (but expired) invoice.

Reproduce:
Scan the invoice from snort after two minutes (expiry 117)
https://snort.social/p/npub14tq8m9ggnnn2muytj9tdg0q6f26ef3snpd7ukyhvrxgq33vpnghs8shy62

![image](https://user-images.githubusercontent.com/43343391/217816446-da6848a0-9ed3-478f-8e1f-0bc92d4c94ad.png)

Would be better if the user would be informed of the problem which is the expiration.

**Comment by Aditi-Singh16** [comment]
In this, I would like to test for expired invoices, how does one have their invoice expire?

**Comment by openoms** [comment]
> In this, I would like to test for expired invoices, how does one have their invoice expire?

One way is to create an invoice with a short expiry and wait.

**Comment by Aditi-Singh16** [comment]
So, I debugged and this snort qr code is not expired but an unknown destination error, so I will add for that condition
