### ISSUE TITLE
Transaction timestamps are incorrect on home screen and transaction list screen

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy-mobile#1106]
The friendly date shown to users on a transaction is incorrect on both home screen and transaction list.  For example I sent the transactions in this screenshot to Nicolas a few days ago.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/3502409/218093833-e28ad177-5071-496d-bd04-7009303f483e.png">

**Comment by nicolasburtey** [comment]
closing for now at it seems it was a local dev/glitch issue
