### ISSUE TITLE
First tap when typing sat amount doesn't do anything

### ISSUE THREAD

**Issue by agbegin** [GaloyMoney/galoy-mobile#1109]
When setting an amount in sats (send flow as well as receive flow), the first tap on the number pad does nothing. You have to tap a second time to get the keyboard to start inputting numbers. 

This is a confirmed issue on iOS, both beta and public releases. Unsure about android. 

https://user-images.githubusercontent.com/90297599/218143852-b24a73b8-d4df-41f7-a6b7-7230ca777284.mov

**Comment by nicolasburtey** [comment]
the new keyboard solved this issue
