### ISSUE TITLE
provide more context when sending money to a username

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#111]
There has been cases when money has been sent to the wrong account. I guess this is the convenience of instant e-money is that now it doesn't take long to send a payment to the wrong account that has a similar name.

One way we can help to prevent that is by providing a bit more context when sending money to a username. One idea: check if the user has already send something to that username or not? if not, we should have maybe a popup saying something like "this is the first time you're sending money to this account. make sure you verify this the right account before proceeding".

**Comment by jrbuhl93** [comment]
For now this can be done by cross-referencing with previous transactions, but once we paginate transactions we may need a new graphql endpoint to make the query.
