### ISSUE TITLE
Pending translations

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy-mobile#113]
**Describe the bug**
Missing translations that require changes in the code:

- "Learn to Earn" button
- "Price for 100,000 sats:" and date labels in chart - price screen
- "digg your way through these lessons and earn" (earn screen)
- "To unlock, answer the question:"(earn screen)
- "pay this business" (map screen)
- RootNavigator Titles:
  - Settings
  - Transaction History
- Default earn transactions (copyBitcoin, whoControlsBitcoin, ..). Not sure how processing descriptions affects app performance but if is not possible we need to add it in the backend
- "You have been logged out" the key is in i18n files but is not used in the alert
- "XXXX is your verification code fore Bitcoin Beach Wallet" SMS (backend) 
- "on_us" types of transaction in payment details
- "User not found" I guess is a backend response, if you can not parse it then maybe we need to add a key/code to the errors thrown by backend (I prefer the key because allow to use directly against i18n component).
- "To" and "From" (transactions in Main screen)
- "a few seconds ago" - "XX minutes ago" (transactions in Main screen)
- in iOS the back button is using "Primary" but I guess is not a missing translation. Maybe we just need to use "common.back"
- "set a note" placeholder in receive screen
- "Hey there! I need some help with Bitcoin Beach Wallet" whatsapp default message

The translations that did not require changes in the code were updated in the PR https://github.com/GaloyMoney/galoy-mobile/pull/112

@nicolasburtey we need to define which term will be used in the app `Sats` or `Satoshis` (including push notifications) and how we will manage backend related translations

**Comment by jrbuhl93** [comment]
Remaining after PR #117 :

> - Default earn transactions (copyBitcoin, whoControlsBitcoin, ..). Not sure how processing descriptions affects app performance but if is not possible we need to add it in the backend
> - "XXXX is your verification code fore Bitcoin Beach Wallet" SMS (backend)
> - "on_us" types of transaction in payment details
> - "User not found" I guess is a backend response, if you can not parse it then maybe we need to add a key/code to the errors thrown by backend (I prefer the key because allow to use directly against i18n component).
> - "To" and "From" (transactions in Main screen)

The last bullet is done on the backend [here](https://github.com/GaloyMoney/galoy/blob/782b62912dcc825f0a722f410443fb41afd9b2f2/src/userWallet.ts#L116)

**Comment by dolcalmi** [comment]
closed in favor of https://github.com/GaloyMoney/galoy/issues/384
