### ISSUE TITLE
using wrong multiplier for phoenix invoices?

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#114]
https://twitter.com/marzsv/status/1419336254651576327?s=20

https://twitter.com/marzsv/status/1419338396972027910?s=20

**Comment by jrbuhl93** [comment]
I just created an account on the Phoenix wallet and tested with a $1.50 invoice generated on the Phoenix Wallet. Both the QR code and the lightning address showed as ~$1.50 in the Bitcoin Beach app, so I haven't been able to reproduce the bug yet. 

I was using this address: 

lnbc43410n1ps0mk98pp5uphdmtuhgg97tu4u8etjuh0te0gsm3gnl4qaexdzv632tjucym8sdqqxqyjw5q9qtzqqqqqq9qsqsp54w07w0ls3krhk95g2wn52jynr5tx2hlq9h9qatxuutmdq5df5k6srzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glcllujrcslldlyd5qqqqlgqqqqqeqqjqkhwrejew8mhdjw5nl7y8nzyvltgr55dnpee97s38qa52wj9y0rfnqcmp8hjvgae5h394xyga9xzmr9xals32f5rmep0vgjpdmelw7eqqqvkqpq

And this QR code:

![image](https://user-images.githubusercontent.com/35902932/126914367-132e544c-3267-4eea-b1d7-043bcba3d6c6.png)


Result:

![image](https://user-images.githubusercontent.com/35902932/126914376-67c6d23c-da05-4394-917a-ce08b4969c55.png)

**Comment by nicolasburtey** [comment]
maybe it's only on Phoenix iOS?

**Comment by jrbuhl93** [comment]
I think it is more likely that when I generated I request. It did so using nano (43410n) I'll verify this.

**Comment by robbiehanson** [comment]
You can reproduce this on Phoenix iOS by typing in an amount such as "0.01 sat". In the real world it is more likely that the user will enter an amount in fiat, and the conversion will result in an amount such as "12,345.01 sat". Either of these amounts currently result an invoice that uses pico.

The code that determines the unit used in the lightning invoice is [here](https://github.com/ACINQ/lightning-kmp/blob/326d1884b7c023a7051580d7682b8717c87eb22f/src/commonMain/kotlin/fr/acinq/lightning/payment/PaymentRequest.kt#L263)
