### ISSUE TITLE
make it possible to force an update for the user

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#1162]
ie: in case of gql deprecation

**Comment by nicolasburtey** [comment]
this has been done on the mobile side. we just need to integrate this into the CI/CD pipeline now.

**Comment by sandipndev** [comment]
Can you explain what is to be done here?
I would like to accelerate this work.

**Comment by nicolasburtey** [comment]
a first iteration on this issue has been done. closing this issue.
