### ISSUE TITLE
"a bug? submit a ticket" in the settings

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#1166]

**Comment by Ayush0054** [comment]
Hey, can I work on this issue? I will show you my approach and then make a pull request

**Comment by nicolasburtey** [comment]
please do!

**Comment by Ayush0054** [comment]
approach :go to setting -> click on "raise ticket" ->navigated to raise ticket screen -> then input your bug through text or images ->  "ticket is raised" feedback message

**Comment by Ayush0054** [comment]
hey @nicolasburtey ,  Could you tell me more about how the ticket is going to be handled? For example, will it be handled using the above approach, an external API, or a custom chat? Any context or leads would be enough for me.

**Comment by nicolasburtey** [comment]
Didn't think thought it much

I think just opening the GitHub page can be enough. Maybe we can add a message saying we are open source which is why it will be opening the webpage to GitHub

**Comment by Ayush0054** [comment]
ok

**Comment by Ayush0054** [comment]
Redirecting to this page ?  Any feedback 
![Screenshot_20230322_033954_Mattermost.jpg](https://user-images.githubusercontent.com/97244608/226753077-01e9d43f-b0c6-4675-92ed-9228d9fd3567.jpg)

**Comment by Ayush0054** [comment]
Sure, I will probably start contributing after some time since I am currently doing an internship and working on personal projects.
