### ISSUE TITLE
Improve pin for current location

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#122]
Currently the current location is shown as a pin that is the same for the merchant, just with a different color (blue instead or red). we want to use something similar to Google Maps and use the compass.

**Comment by MikeMwambia-TrojanSystem** [comment]
More details please

**Comment by jrbuhl93** [comment]
I think this is referring to the icon that shows your current location on the map screen. Instead of a blue colored pin, it should be what is used in google and apple maps.

Our app:

![Blue pin from iOS](https://user-images.githubusercontent.com/35902932/129904599-58d9831a-f88b-4ba3-a7a9-5848e204dcdf.png)

Apple maps:

![Apple map from iOS](https://user-images.githubusercontent.com/35902932/129904632-02de5b6e-9693-471e-869a-0978f77c018c.png)

**Comment by MikeMwambia-TrojanSystem** [comment]
Got it

**Comment by MikeMwambia-TrojanSystem** [comment]
![PinLocation](https://user-images.githubusercontent.com/5917824/130427651-7ffc1c1a-ddfd-4931-9f16-2606239f5024.png)

This is the best image I can get for the icon better suggestions are welcome..

**Comment by MikeMwambia-TrojanSystem** [comment]
@jrbuhl93 according to [this](https://github.com/react-native-maps/react-native-maps/blob/master/docs/marker.md) , I think there are 2 approaches to use `image` or `icon` , what do you think ?

**Comment by jrbuhl93** [comment]
I think we should use `showsUserLocation` in [MapView](https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md).

**Comment by MikeMwambia-TrojanSystem** [comment]
Did I miss something because to my understanding [on this code](https://github.com/GaloyMoney/galoy-mobile/blob/73b96b738855fceccacb3580923ad10b9f42c63c/app/screens/map-screen/map-screen.tsx#L108) it gives the current location and to have a custom pin we need to reference an image , is that so ?

**Comment by jrbuhl93** [comment]
You are correct. But I think Nicolas may have done this because he didn't see the `showsUserLocation` in`MapView`. This makes all the code to create the blue pin unnecessary (assuming `showsUserLocation` works well).

**Comment by MikeMwambia-TrojanSystem** [comment]
Okay got it.
Thank you.
