### ISSUE TITLE
Switching between sats and USD when updating amount in receive screen doesn't work properly

### ISSUE THREAD

**Issue by Extheoisah** [GaloyMoney/galoy-mobile#1229]
when you try to update the invoice amount, and switch between USD and BTC, the amount doesn;t update properly at first but picks up later.
See video attached

https://user-images.githubusercontent.com/60826700/220603899-abd9dc22-e2f5-4544-a253-d1b6f7c65e14.MP4

**Comment by nicolasburtey** [comment]
when a payment is succesful, we should return to the home automatically @Extheoisah 

the fact we go from BTC to USD without having to go through the home through the test is actually an artefact of the bug above.

**Comment by Extheoisah** [comment]
I agree that we should modify the code to go the home screen on every successful payment. But I don't understand how it relates to the issue above.

This issue happens when you try to update an amountless BTC invoice. When you enter an amount and switch between units, the value doesn't appear or update. We currently don't test this part of the code in the e2e test. So I can write a test for it.

> when a payment is succesful, we should return to the home automatically @Extheoisah
> 
> the fact we go from BTC to USD without having to go through the home through the test is actually an artefact of the bug above.

**Comment by nicolasburtey** [comment]
> I agree that we should modify the code to go the home screen on every successful payment. But I don't understand how it relates to the issue above.
> 
> This issue (as described above) happens when you try to update an amountless BTC invoice. When you enter an amount and switch between units, the value doesn't appear or update. We currently don't test this part of the code in the e2e test. So I can write a test for it.
> 
> > when a payment is succesful, we should return to the home automatically @Extheoisah
> > the fact we go from BTC to USD without having to go through the home through the test is actually an artefact of the bug above.

you're right. nevermind. 
should have pay attention to the video.
