### ISSUE TITLE
Have a way to hide the balance

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#126]
when paying an invoice in person, in many scenarios, people around the payer/payee can see the balance of both the payer/payee. this is not ideal when someone has a large balance. 

we should have a way to hide the balance in the settings, and only show it after clicking on the balance/an eye icon, or something along those lines.

I think this can be a setting only saved in the mobile app.

**Comment by jrbuhl93** [comment]
Added in #181
