### ISSUE TITLE
QR code doesn’t show the invoice as uppercase 

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#127]
I thought we had added this @jrbuhl93 ?

**Comment by jrbuhl93** [comment]
It does based on the code [here](https://github.com/GaloyMoney/galoy-mobile/blob/68715944244768d3b88930e2b75b0ed06ab545b5/app/screens/receive-bitcoin-screen/receive-bitcoin-screen.tsx#L435). But the code [copied to clipboard](https://github.com/GaloyMoney/galoy-mobile/blob/68715944244768d3b88930e2b75b0ed06ab545b5/app/screens/receive-bitcoin-screen/receive-bitcoin-screen.tsx#L372) and [shown below the qr code](https://github.com/GaloyMoney/galoy-mobile/blob/68715944244768d3b88930e2b75b0ed06ab545b5/app/screens/receive-bitcoin-screen/receive-bitcoin-screen.tsx#L463) are still lower case. 

We also added converting to lowercase in parsing a destination ([validatePayment](https://github.com/GaloyMoney/galoy-mobile/blob/ed81858437e0619c3f881bbe002012cb175e54c0/app/utils/parsing.ts#L75)). So the uppercase QR is being converted after scanning it.

**Comment by nicolasburtey** [comment]
> So the uppercase QR is being converted after scanning it.

yup I got this after more testing. thanks.
