### ISSUE TITLE
Unable to scan/paste bitcoin address when default wallet set to USD

### ISSUE THREAD

**Issue by agbegin** [GaloyMoney/galoy-mobile#1290]
**Describe the bug**
Bug found in iOS, v2.1.56 build 427
With default wallet set to USD, an error screen is thrown when trying to pay to a bitcoin address: 

**To Reproduce**

1. Set default wallet to USD (within merchant features in settings)
3. Click on Send
4. Scan or paste a bitcoin address 
5. See error

**Expected behavior**
Expect to continue with payment flow, with bitcoin account selected as the send from account if that's the only account i can send onchain payments from.

**Screenshots**
![IMG_2824](https://user-images.githubusercontent.com/90297599/221958397-d4da2666-0dd3-48f0-a242-747829f85064.PNG)

**Smartphone (please complete the following information):**

- Device: iphone 11
- OS: iOS 15.6.1
- Version:  Bug found in iOS, v2.1.56 build 427

**Comment by nicolasburtey** [comment]
issue is here @UncleSamtoshi : https://github.com/GaloyMoney/galoy-mobile/blob/main/app/screens/send-bitcoin-screen/payment-details/onchain.ts#L40

related to the recent refactoring. wondering if there is an easy fix or if we should wait for doing the onchain send from stablesats

**Comment by UncleSamtoshi** [comment]
@nicolasburtey I think there should be an easy fix. We should probably halt the most recent rollout till this fix is put through. The scope is anyone scanning an onchain address with usd as their default wallet.

**Comment by Extheoisah** [comment]
closed by https://github.com/GaloyMoney/galoy-mobile/pull/1293
