### ISSUE TITLE
Uppercase for qrcode

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#13]
many low end android device are being used in developing country like El Salvador.

Optimizing the QR code would allow low end care to have better odds to correctly capture the QR code showed on another phone. 

more info: https://bitcoinops.org/en/bech32-sending-support/

**Comment by dannyjmac** [comment]
[PR in](https://github.com/GaloyMoney/galoy-mobile/pull/74) for this issue.
