### ISSUE TITLE
Incorrect amount in transaction history when display currency is not USD

### ISSUE THREAD

**Issue by Extheoisah** [GaloyMoney/galoy-mobile#1308]
**Describe the bug**
*Note: display currency is still in beta*
When you make a transaction with your currency set to another denomination other than USD, the amount shown in the transaction history is denominated in USD not the set display currency.

**Screenshots**
![IMG_0032](https://user-images.githubusercontent.com/60826700/222419395-8c31ba73-42ed-4505-95aa-adffaa7bf6f1.PNG)

- Device: iPhone XS Max
- OS: 16.3.1
- Version 2.1.59 build 433

**Comment by nicolasburtey** [comment]
this is known @Extheoisah. it's because the development on the backend has not been completed on this. closing for now as it's in progress on our board.
