### ISSUE TITLE
wrong keyboard for receiving money

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#131]
We should have a digit only keyboard.

Not sure if that matters but it's on a Huawei phone.

**Comment by nicolasburtey** [comment]
![Uploading 85553E2A-BD51-4299-B639-15866117ADC8.jpeg…]()

**Comment by jrbuhl93** [comment]
I think that github stops attempting to upload after you submit the comment, so you have to wait to post the comment until after the upload is done.

**Comment by nicolasburtey** [comment]
![Uploading A7CDB31F-6730-406C-89CC-10E225D65372.jpeg…]()

**Comment by jrbuhl93** [comment]
![Image from iOS](https://user-images.githubusercontent.com/35902932/127883107-35a11ded-eef8-4130-94cf-44d5459a71fd.jpg)

**Comment by jrbuhl93** [comment]
I was not able to reproduce this issue, and the code looks like the app should be using number-pad for all input payments.
![Screenshot_20210811-080534](https://user-images.githubusercontent.com/35902932/129036102-b2b9d944-7ffb-4d34-90bf-5de890aa3019.png)

**Comment by MikeMwambia-TrojanSystem** [comment]
Does not reproduce on ios...
![ioskeyboard](https://user-images.githubusercontent.com/5917824/129885498-9f88b238-aa6b-4c15-8596-4e722b6ddea7.jpeg)

**Comment by MikeMwambia-TrojanSystem** [comment]
On the same input issues is the network fee automatically selected or is it an input by the user , on it doesn't seem to allow input or automatically fill the network fee
![networkFee](https://user-images.githubusercontent.com/5917824/129887592-b547437e-d8db-4ca4-ad83-4eb83a35021c.jpeg)
