### ISSUE TITLE
Regression: no longer a pop up when an invoice is in clipboard 

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#140]
**To Reproduce**
1. Create an invoice from another wallet
2. Copy to the clipboard 
3. Open bitcoin beach wallet 
4. There should be a pop up but this is no longer the case

**Comment by jrbuhl93** [comment]
This was fixed in the PR #138. Would you like me to release it immediately? I would like to release #128 (after fixes if necessary) with it.

**Comment by nicolasburtey** [comment]
not an urgent issue IMO. you can still paste the invoice manually.
