### ISSUE TITLE
Balance doesn’t refresh automatically

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#141]
It seems the problem occurs both when sending a payment and receiving a payment.

For sending the problem doesn’t seems fully deterministic. Salim says the balance would refresh “some times”. Maybe 20% of the time.

Refreshing the wallet by scrolling down/triggering the “refresh” wheel solve the problem. But this is not intuitive for everyone.

the problem is occurring on Android phones. It may matter because the notification system is OS dependant

**Comment by jrbuhl93** [comment]
Is it only for a certain type of transaction. If it is an onUs/intraLedger transaction, is there a push notification involved?

**Comment by nicolasburtey** [comment]
I just pay the restaurant tonight and can reproduce the issue with my phone (iPhone). 

The transaction was intraledger
