### ISSUE TITLE
Only generate onchain address if it needs to be displayed

### ISSUE THREAD

**Issue by jrbuhl93** [GaloyMoney/galoy-mobile#146]
Limiting the amount of onchain addresses generated would help with [database management.](https://github.com/GaloyMoney/galoy/pull/421/files#r684342445)

**Comment by nicolasburtey** [comment]
I think the way this could work is that the onchain address could be generated only if the user swipe right on the receive screen and tap "generate a onchain address" button. 

there is probably no need to change the backend for this.

**Comment by MikeMwambia-TrojanSystem** [comment]
On the receive bitcoin screen currently has 2 navigation i.e share lightning invoice and share bitcoin address you suggesting a third one with generate onchain address button @nicolasburtey

**Comment by daviroo** [comment]
This issue was fixed in #250.  There is now a button displayed to give the user the option to generate an unchain address.
