### ISSUE TITLE
use biometrics if available when opening the application

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#15]
We are adding a 2fa to validating large payment, but it would be a good features that would add security easily if we could ask for the biometrics at the launch of the app.

we have a lot more user on Android, so we could start with Android first.

**Comment by jrbuhl93** [comment]
#58 addressed this issue, but we still want authentication when returning from the background state after a period of time.

**Comment by nicolasburtey** [comment]
has been integrated
