### ISSUE TITLE
The 'to' field on the send screen should have '...' in the middle for long inputs

### ISSUE THREAD

**Issue by jrbuhl93** [GaloyMoney/galoy-mobile#150]
This would allow screenshots to show whether the 'to' field is an onchain or lightning address.

**Comment by nicolasburtey** [comment]
I'm not sure this is very needed any more. at least not as much as before. 

now that we show the beginning of the inputs, we can see whether what has been pasted is an invoice or an onchain address. 

I think it could be useful for onchain to verify the full address. someone sending to a hardware wallet may want to check the first 6 characters and last 6 characters for instance.
