### ISSUE TITLE
"To" field can no longer be used after clear

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy-mobile#152]
**Describe the bug**
If you paste an invoice and tap X (to clear the field), the field can no longer be used

**To Reproduce**
1. Go to Send screen
2. Click on To field and paste an invoice
3. Click on X to clear the field (invoice)
4. Try pasting again or type in the field 

To make it work again you must go back to home and go to Send again

**Expected behavior**
You should be able to clear the To field and type or paste again

**Smartphone**
 - Device: iPhone Xs
 - OS: iOS 14.6
 - Version 1.4.7 build 254

**Comment by nicolasburtey** [comment]
build 254 is a (fairly) old build? can you try with the last version?

**Comment by dolcalmi** [comment]
> build 254 is a (fairly) old build? can you try with the last version?

I am using test flight version but seems to happen too in 1.4.9
