### ISSUE TITLE
Remove lodash

### ISSUE THREAD

**Issue by jrbuhl93** [GaloyMoney/galoy-mobile#171]
To minimize external imports we should use javascript instead of lodash where possible.

**Comment by danwebb1** [comment]
Would it be appropriate to have a subdirectory under utils for functions written to replace lodash and then just work through the project as able?

**Comment by jrbuhl93** [comment]
In this commit, not yet merged, Samer replaced importing all of lodash with just importing the functions we needed. What would be preferred is to use native javascript functions instead of lodash. If needed we can make our own functions under utils, but I think a lot of them may be doable in javascript.
