### ISSUE TITLE
LBP fiat currency addition

### ISSUE THREAD

**Issue by marcondy** [GaloyMoney/galoy-mobile#1741]
It would be great to have integrated the real market rate (locally named Black Market) of LBP ( Lebanese Lira )

Unfortunately Google and popular api do not display the correct value, they display only what central bank has set, and that rate is not in line with actually market rate of LBP/USD

[API documentation](https://yadio.io/api.html)

https://api.yadio.io/convert/1/BTC/LBP

Thank you in advance.

**Comment by nicolasburtey** [comment]
Thanks for the request

Some questions

How big is the difference in %? 

Does the difference changes frequently?

Would you use both rate if there were available or only yadio?

**Comment by marcondy** [comment]
The official rate is :
15,000 LBP per $1

Unofficial:

108,000 LBP per $1

720% difference.

Since our crisis that started over 3 years ago, they changed the official rate once and that was on February 2023.

The street value of use changes on daily basis, we had a 40% increase 10 days ago hitting ATH followed by a drop.

No one uses official rate, it would be a 86% loss of purchasing power to the dollar.

**Comment by marcondy** [comment]
> Thanks for the request
> 
> Some questions
> 
> How big is the difference in %?
> 
> Does the difference changes frequently?
> 
> Would you use both rate if there were available or only yadio?

The official rate is :
15,000 LBP per $1

Unofficial:

108,000 LBP per $1

720% difference.

Since our crisis that started over 3 years ago, they changed the official rate once and that was on February 2023.

The street value of use changes on daily basis, we had a 40% increase 10 days ago hitting ATH followed by a drop.

No one uses official rate and there is no use for it, it would be a 86% loss of purchasing power to the dollar.

**Comment by nicolasburtey** [comment]
> > Thanks for the request
> > Some questions
> > How big is the difference in %?
> > Does the difference changes frequently?
> > Would you use both rate if there were available or only yadio?
> 
> The official rate is : 15,000 LBP per $1
> 
> Unofficial:
> 
> 108,000 LBP per $1
> 
> 720% difference.
> 
> Since our crisis that started over 3 years ago, they changed the official rate once and that was on February 2023.
> 
> The street value of usd changes on daily basis, we had a 40% increase 10 days ago hitting ATH followed by a drop.
> 
> No one uses official rate and there is no use for it, it would be a 86% loss of purchasing power to the dollar.

can you try again and let us know if the rate is more accurate? it's now using Yadio for LBP: https://github.com/GaloyMoney/price/commit/edcb4741a1dee75fa07a69f350def26147884e40

**Comment by nicolasburtey** [comment]
closing for now. can reopen if more work is needed on this one.
