### ISSUE TITLE
Conversion input bug

### ISSUE THREAD

**Issue by vindard** [GaloyMoney/galoy-mobile#1750]
Bug when you start at fiat input, switch to sats input, and then switch back to fiat input.

https://user-images.githubusercontent.com/17693119/228175608-650c870e-88bc-485b-a1aa-585374ff7c5e.mp4

**Comment by Extheoisah** [comment]
I don’t seem to understand the bug. Can you give more context?

**Comment by nicolasburtey** [comment]
won't fix @vindard as we've replaced the input component, but please reopen a new issue if similar issue persists
