### ISSUE TITLE
We should advertise the tipping/link to the user for lnpage

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#182]
https://twitter.com/theguyswann/status/1433934882221273091?s=21

maybe have a link for it in the settings page so people are aware of this option

**Comment by danwebb1** [comment]
I have a working prototype, so to speak, on this [branch] (https://github.com/danwebb1/galoy-mobile/tree/feature_advertise_copy_tip_link). I am having environment issues with Android locally so I have to deal with that when I get free time. Needs to be tested on Android and polished but its close. If anyone else can finish this off quickly, feel free to use or lose what I started!
