### ISSUE TITLE
Login screen is not showing errors

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy-mobile#186]
**Describe the bug**
If we return an error from backend the user is not receiving feedback

**To Reproduce**
1. Go to login screen
2. Request phone code (do a lot of requests to hit `TOO_MANY_REQUEST` error)

**Expected behavior**
show an error message.  (something similar to "connection issue. Verify your internet connection")

**Additional context**
Backend PR [555](https://github.com/GaloyMoney/galoy/pull/555)

**Comment by daviroo** [comment]
Hey 👋 - I could take this one as a first issue.
