### ISSUE TITLE
Can't unlock if fingerprint fails

### ISSUE THREAD

**Issue by openoms** [GaloyMoney/galoy-mobile#1874]
**Describe the bug**
There is no fallback to PIN when the Unlock with the fingerprint reader fails.

**To Reproduce**
* Open BBW
* Attempt to unlock with and unregistered fingerprint a a fee times
* Clicking unlock does not open anything afterwards

**Expected behavior**
Fall back to PIN if the fingerprint is not working.

**Smartphone**
- Device: Google Pixel 3
- OS: GrapheneOS
- Version: Android 12

**Additional context**
App version: 2.2.13 (internal alpha)
Just pinging @UncleSamtoshi who I believe was last working on this.

**Comment by openoms** [comment]
Found the solution so closing.

Was able to reenable the fingerprint sensor after locking and unlocking the phone home screen with PIN -> the fingerprint unlock works again.

Found that the `PIN Code` was not active in the `Security` menu which was the reason it couldn't be used as a fallback.

Tested to disable the fingerprint sensor with wrong ties again and can confirm that if the PIN is set beforehand the app can be unlocked with PIN regardless of the sensor being disabled.

**Comment by openoms** [comment]
On a second thought in case the fingerprint sensor is permanently damaged would be good to have a PIN available.

Should we force the PIN to be created when enabling the `Biometric` login ?

**Comment by nicolasburtey** [comment]
> On a second thought in case the fingerprint sensor (or finger) is permanently damaged would be good to have a PIN available otherwise the user can be locked out of the app.

feels an edge case that if we cover would 1/ increase complexity and 2/ add burden on the user? ie: like if the phone is broken, it's expected someone will have to log back in eventually?
 
> Should the PIN creation be forced when enabling the `Biometric` login ?

**Comment by Extheoisah** [comment]
> On a second thought in case the fingerprint sensor (or finger) is permanently damaged would be good to have a PIN available otherwise the user can be locked out of the app.
> 
> Should the PIN creation be forced when enabling the `Biometric` login ?

I am in favour of enforcing PIN creation when enabling Biometrics. Most fintech apps I've used have the PIN number pad overlaid in the background incase biometric fails. This would also be a good use case for people who have damaged biometric sensors (either Face ID or fingerprint).

**Comment by openoms** [comment]
yes, it is not just about the phone being damaged but the usecase eg. using glasses, hat, mask or gloves which would alter the biometrics even temporarily and cause inconvenience. Having a fallback is the usual practice.

**Comment by MaxwellDG** [comment]
#2960 Partially addresses this; at least makes the process smoother. If a user's biometric isn't working for whatever reason, there is the pin option (if enabled) or they can log out and log back in like they normally would. They can receive a code to their device or email
