### ISSUE TITLE
Logout when token is invalid

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy-mobile#190]
**Describe the bug**
Support has received multiple cases with the recent problems in backend related to invalid token (in context), if the user can't request its data then the balance and transactions appears empty(zero) so we need to logout the user if we have this problem 

**To Reproduce**
1.  Using local environment, log in with a test user
2. After being logged in reset the local test enviroment `TEST="01|02" make reset-integration` (this will reset user ids and current token will be invalid)
3. Refresh balance/transactions

**Expected behavior**
Logout if invalid token

**Comment by daviroo** [comment]
Fixed in #281
