### ISSUE TITLE
Arrow next to lnurl address is confusing

### ISSUE THREAD

**Issue by krtk6160** [GaloyMoney/galoy-mobile#1968]
The arrow on the rightmost side of the "Your BBW address" list item in the settings page is confusing because it doesn't take you to another screen like other list items, but rather copies the address to your clipboard.

**Comment by Aditi-Singh16** [comment]
Should it be replaced with a copy icon instead?

**Comment by Ahmadkhan02** [comment]
![share](https://user-images.githubusercontent.com/75062775/233334589-04335cae-f2c0-4a69-8235-da86025afa9c.png)

What about something like this icon?
