### ISSUE TITLE
automatically suggest retrying send text after 60 sec

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#210]
Sometimes, text doesn't arrive to the mobile phone. One way to improve this is to suggest trying to send the text another time after a delay. 

If the phone was not accessible by the carrier initially, 1 min after this could work better.

We could suggest sending back the text after 1 minutes, by having a timer on the text confirmation screen.

**Comment by maxghafori** [comment]
[PR 212](https://github.com/GaloyMoney/galoy-mobile/pull/212)
