### ISSUE TITLE
Remove BitcoinBeachMarketing from contacts

### ISSUE THREAD

**Issue by jrbuhl93** [GaloyMoney/galoy-mobile#215]
An account with the username BitcoinBeachMarketing does a lot of transactions with users because it pays out quiz rewards. Having BitcoinBeachMarketing as a contact isn't desirable because it can lead to accidental payments and take up space in users' contacts list. We should filter out "BitcoinBeachMarketing" from displayed contacts.

**Comment by nicolasburtey** [comment]
note: long term we could have a property in the backend to avoid a user being added as a contact
