### ISSUE TITLE
Bottom navigator icon labels

### ISSUE THREAD

**Issue by samerbuna** [GaloyMoney/galoy-mobile#217]
Bottom navigator icon labels do not change when switching language (they do after restarting the app).

**Comment by PuneetDabral** [comment]
can i do my first contribution here ...but i need your support

**Comment by DugarRishab** [comment]
@samerbuna hey, I want to work on this issue, can you please assign this to me?

**Comment by Ahmadkhan02** [comment]
This issue seems to have been fixed as the language change seems to be working now

**Comment by nicolasburtey** [comment]
thanks. closing this
