### ISSUE TITLE
chore: NFC improvment

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#2284]
- add audio when the NFC is read
- remove the "NFC read"

for browser
- after permission has been asked, should always get the NFC enabled when receiving payments

**Comment by agbegin** [comment]
Additional NFC improvements: 

- Enable paying by NFC in main receive flow: 
    1. Tap receive
    2. Enter amount
    3. Invoice is shown (show "NFC" text and icon which is not necessary to push, but brings up OS prompt that NFC is ready)
    4. Sender taps NFC card to device 
    5. Redeem sats confirmation screen is shown with amount filled in (Sender or receiver can tap to confirm the tx) 
    6. Confirmation screen/checkmark
    
- Enable "print receipt" function upon confirmation.  
    1. Include the data from transaction detail
    2. Add the original lightning invoice (apparently BTCPay does this.. it has been requested by customer)

**Comment by nicolasburtey** [comment]
closing this one down. NFC has been added to the POS
