### ISSUE TITLE
[bug]: transaction history pagination not working

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy-mobile#2295]
**Describe the bug**
Transaction history is only getting the first page of transactions

**To Reproduce**

1. Go to Transactions
2. Scroll down to the bottom and try to get more transactions

**Expected behavior**
Paginate properly transaction history

**Smartphone:**

- Device: iPhone Xs
- Version 2.2.59.511

**Comment by nicolasburtey** [comment]
I can reproduce. Seems a fairly critical bug. 

Have you checked whether the api is working ok?

**Comment by nicolasburtey** [comment]
should be fixed by https://github.com/GaloyMoney/galoy/pull/2714
