### ISSUE TITLE
Double tapping input box doesn't select entire string

### ISSUE THREAD

**Issue by krtk6160** [GaloyMoney/galoy-mobile#2298]
**Describe the bug**
Double tapping inside destination input box does not select entire string.

**To Reproduce**

- video attached in screenshots section

**Expected behavior**
Entire string should be selected when double tapping the string inside the input box.

**Screenshots**

https://github.com/GaloyMoney/galoy-mobile/assets/17320781/ccefb7d3-2285-4bde-b28d-061c198af3ca

**Smartphone (please complete the following information):**

- Device: S21 5G
- OS: Android 12

**Comment by MaxwellDG** [comment]
@krtk6160 Are you still experiencing this behaviour? I'm a bit confused here because in the video you posted it looks like 3 out of 4 times you tapped/double-tapped it did select the entire string. And I've tested it on two android devices and a double-tab is selecting the entire string.

Regardless, I can see this component needs some work. Things I've fixed so far:
- There was a 1px jump from borderWidth on pasting
- Buttons didn't have opacity indication when being pressed
- Added a toast so user's know what's happening when they press the paste button
- Double pressing paste button was confusing the validation process and removing it on 2nd press (it went into manual 'entering' mode)

**Comment by nicolasburtey** [comment]
still seeing the same behavior by checking out from this PR

https://github.com/GaloyMoney/galoy-mobile/assets/11156370/20ad00c6-1255-46d7-9f1c-5d4df1569dca

**Comment by MaxwellDG** [comment]
I've tried for a while now to get this working smoothly, but there's consistently some shortcomings.

Most solutions involved the prop **selection**, or forcing focus() but these all resulted in regressions elsewhere. The main issue is that the context menu can't be controlled by React Native in any reasonable manner. On top of that, the context menu behaves differently on different devices.

I can think of two possible solutions, but they are tedious so I'd like confirmation that it's worthwhile before I attempt them.
- A custom made context menu. We could disable the native context menu and create our own with all the 'copy', 'paste' etc... options
- Native modules. In Android you can control the context menu programmatically https://developer.android.com/reference/android/app/Activity.html#openContextMenu%28android.view.View%29
On iOS it's a bit easier apparently and you can control the contextMenu with ActionSheetIOS.showActionSheetWithOptions

**Comment by nicolasburtey** [comment]
> I've tried for a while now to get this working smoothly, but there's consistently some shortcomings.
> 
> 
> 
> Most solutions involved the prop **selection**, or forcing focus() but these all resulted in regressions elsewhere. The main issue is that the context menu can't be controlled by React Native in any reasonable manner. On top of that, the context menu behaves differently on different devices.
> 
> 
> 
> I can think of two possible solutions, but they are tedious so I'd like confirmation that it's worthwhile before attempting one.
> 
> - A custom made context menu. We could disable the native context menu here and create our own with all the 'copy', 'paste' etc... options
> 
> - Native modules. In Android you can control the context menu programmatically https://developer.android.com/reference/android/app/Activity.html#openContextMenu%28android.view.View%29
> 
> On iOS it's a bit easier apparently and you can control the contextMenu with ActionSheetIOS.showActionSheetWithOptions
> 
> https://stackoverflow.com/questions/46735809/opening-context-menu-on-long-press-in-react-native
> 
> 
> 
> **Third option**
> 
> Remove the context menu entirely and just add a third icon for copying the whole string to clipboard.

I'm wondering how many users are facing this issue and whether this is worth doing a custom module or component for it

One use case I see for this would be a QR code scanner, but the string is then passed down to the next screen automatically. The "fix" for that would be to make the destination on the next screen copyable, maybe with a copy icon like we have in the tx detail screen.

**Comment by MaxwellDG** [comment]
> > I've tried for a while now to get this working smoothly, but there's consistently some shortcomings.
> > Most solutions involved the prop **selection**, or forcing focus() but these all resulted in regressions elsewhere. The main issue is that the context menu can't be controlled by React Native in any reasonable manner. On top of that, the context menu behaves differently on different devices.
> > I can think of two possible solutions, but they are tedious so I'd like confirmation that it's worthwhile before attempting one.
> > 
> > * A custom made context menu. We could disable the native context menu here and create our own with all the 'copy', 'paste' etc... options
> > * Native modules. In Android you can control the context menu programmatically https://developer.android.com/reference/android/app/Activity.html#openContextMenu%28android.view.View%29
> > 
> > On iOS it's a bit easier apparently and you can control the contextMenu with ActionSheetIOS.showActionSheetWithOptions
> > https://stackoverflow.com/questions/46735809/opening-context-menu-on-long-press-in-react-native
> > **Third option**
> > Remove the context menu entirely and just add a third icon for copying the whole string to clipboard.
> 
> I'm wondering how many users are facing this issue and whether this is worth doing a custom module or component for it
> 
> One use case I see for this would be a QR code scanner, but the string is then passed down to the next screen automatically. The "fix" for that would be to make the destination on the next screen copyable, maybe with a copy icon like we have in the tx detail screen.

Yes I certainly agree that there are better solutions for this than to aggressively force the double-tap to do what we want. And the only scenario anyone would be copying instead of pasting would be from a QR.

I'll add that copy to clip board icon to the next screen destination field and call it a day on this issue
