### ISSUE TITLE
chore: remove hardcoded string in earn

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#2319]
https://github.com/GaloyMoney/galoy-mobile/blob/main/app/screens/earns-map-screen/bottom-start-01.en.svg

contains a string hardcoded in english. there is another version for spanish. but we should make it translatable, or alternatively not show any string in non english/spanish version.

**Comment by MaxwellDG** [comment]
Additional chore here is when user is in 'Explore wallet' mode. Pressing the first section 'Bitcoin: What is it?' shouldn't have the new popup saying "This section will be available tomorrow!". I'll put a flag there so the user can go through to the next screen, where they'll be met with the correct blocking popup that says something like 'make a real account to proceed'.

**Comment by MaxwellDG** [comment]
I also don't know why this text is in an .svg in the first place but I'll continue doing it as such anyways. It'd be able to be centered regardless of the language if it weren't.
