### ISSUE TITLE
trial mode onboarding - potential improvements

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#2345]
- in the Settings screen, on Account line, and in the Account screen, on Backup/upgrade account, add an ⚠️ sign (only if on level 0)
- I'm not a fan of the phone icon for Backup/upgrade account. I don't think it convey the right message. I'm not sure which icon we could replace it with (I know it's here probably because it share the same state as where the phone number has been entereted). maybe `person-circle-outline` from ionicons is a better ? we will eventually also have email here so we could prepare for that at the same time.
- modal "Upgrade your account" has light grey title but white text. I think all should be white (or all light grey) - but the title should never be less visible in term of opacity than the text associated with it
- this PR didn't work. https://github.com/GaloyMoney/galoy-mobile/commit/649557187c2d7344fc77d640b345b7ba5e6e106a still flickering on app start
- I think the "upgrade your account modal" is good in place where we want to suggest to user to upgrade (ie: receive onchain), but it's not the best message for when the user is on the Account screen and tap on Upgrade. It's conflating 2 uses cases: marketing message (which is what this screen is designed for, as it is currently) and set the expectation when the user already shows the intent to upgrade. If we want to set expectation in the upgrade flow, when the user shows the intent to upgrade, then we can have an additional screen, probably not in modal but as a standard screen, that would sit prior to the "enter your phone" screen, with a text along the line:

title: "You're going to upgrade your account"
text: "Upgrading your account make your account recoverable. You will do this by verifying your phone number in the follow screen. It also give you higher transactions limits and more functionality"

other improvements:
- in the Account screen swap Account level with Backup/upgrade account, so that all actionable items are grouped together

**Comment by UncleSamtoshi** [comment]
Are you saying that you want  ⚠️  and  "person-circle-outline" for Backup/upgrade account?

**Comment by nicolasburtey** [comment]
> Are you saying that you want warning and "person-circle-outline" for Backup/upgrade account?

I think the warning could be within the text (at the end of it) if we're on level 0.
