### ISSUE TITLE
Add Support to "Need help? Contact us." section in settings

### ISSUE THREAD

**Issue by pretyflaco** [GaloyMoney/galoy-mobile#2384]
Should be as follows so 1:1 support requests do not land in Telegram community chat. Suggested changes highlighted in bold below.

Status Page
Telegram (Community)
WhatsApp **(Support)**
Email **(Support)**

![image](https://github.com/GaloyMoney/galoy-mobile/assets/32958103/6dc05c48-21ab-4507-aab3-803ecdc2af5c)

**Comment by nicolasburtey** [comment]
there are been some changes here, closing this ticket as probably not relevant any more

but @pretyflaco feel free to re-open if needed.
