### ISSUE TITLE
Fix Jitter on all Modals

### ISSUE THREAD

**Issue by sandipndev** [GaloyMoney/galoy-mobile#2405]
The reason there's a jitter on close/open of modal is because we often don't render the modal when the state to show it's visibility is set to false.

#### What we do
```tsx
{showModal && <ReactNativeModal isVisible={showModal} ... />}
```

Because of this what happens is there's a re-render when the modal is toggled and the animation in/out couldn't be played properly. This causes the experience to be a little jittery especially on slower phones.

#### What we should do
```tsx
<ReactNativeModal isVisible={showModal} ... />
```

This would handle the animation as well nicely.

**Comment by Aditi-Singh16** [comment]
1. AmountInputModal
2. AppUpdateModal
3. CustomModal
4. Stablesats
5. EarnQuiz
6. ContactModal
7. SetLightningAddressModal
8. ChooseWalletModal
9. ModalNfc
10. AccountDeletionModal
11. UpgradeAccountModal

@sandipndev are these all the Modals to modify?

**Comment by sandipndev** [comment]
Yup, that should be all @Aditi-Singh16
