### ISSUE TITLE
Debounce the username input action (which hits the API)

### ISSUE THREAD

**Issue by samerbuna** [GaloyMoney/galoy-mobile#246]
Right now, the API gets hit on every letter typed in the username field in the send screen.

Change it so that the API is hit only when the user stop typing for 1 second.

Use `lodash.debounce`

**Comment by rimbener** [comment]
I think this was fixed in [Debounce the To field in Send Bitcoin screen](https://github.com/GaloyMoney/galoy-mobile/pull/250/commits/9484cfb2e68f902e5e3c8e097a00d93ded316adc)

**Comment by samerbuna** [comment]
@rimbener yep. Thanks!
