### ISSUE TITLE
Improve "hide balance" interactions based on user feedback

### ISSUE THREAD

**Issue by agbegin** [GaloyMoney/galoy-mobile#2460]
Users have reported issues with how hide balance feature works: 

1. When user has set "hide balance" in security, they would like for balances also to be hidden in the account selector in the Send flow 
2. When user taps balance on home screen to hide their balance, expectation is that recent transactions should also be hidden
3. When user hides their balance, closes the app, and re-opens the app, expectation is that the app remembers they toggled hide balance on last time they used the app. (even if default hide balance set to off)

**Comment by UncleSamtoshi** [comment]
Do you think its best to just have a global switch where everything is showing or nothing is showing? The per field override gets confusing, especially on the home screen for point 2 where people are expecting the transactions to be hidden when hiding the balance.

**Comment by agbegin** [comment]
> Do you think its best to just have a global switch where everything is showing or nothing is showing? The per field override gets confusing, especially on the home screen for point 2 where people are expecting the transactions to be hidden when hiding the balance.

Yes I think hide all or show all is appropriate. Imagine the use case will generally be, you have a moment to make sure your screen is not being looked at before you reveal balances/txns.
