### ISSUE TITLE
When setting custom amount allow pasting sat amount

### ISSUE THREAD

**Issue by pretyflaco** [GaloyMoney/galoy-mobile#2497]
**Is your feature request related to a problem? Please describe.**
Inputting a specific amount during invoice creation

**Describe the solution you'd like**
Allow pasting amount from clipboard

**Describe alternatives you've considered**
TINA

**Additional context**
E.g. Robosats contract step for bonding on buyer side requires specific sat amounts to be entered, and there are users asking for this feature for more convenience and usability - see https://twitter.com/eko2one/status/1681745875737903105

**Comment by MaxwellDG** [comment]
I'll switch the **Text** components to **Input** components that have their state shared with the number pad. This should allow for pasting values in both the SAT and currenecy of choice fields
