### ISSUE TITLE
Exported csv filename

### ISSUE THREAD

**Issue by vindard** [GaloyMoney/galoy-mobile#2501]
I noticed that we export the csv file as simply `export` on iOS. Is it from here ([L135](https://github.com/GaloyMoney/galoy-mobile/blob/83faec0c1c71c01e6003ccb079b99c5e3ef88619/app/screens/settings-screen/settings-screen.tsx#L135C13-L135C13))?

**Comment by nicolasburtey** [comment]
yup. I remember there was some issue with the extension but I look back at this 2+ years ago, so we might want to revisit. 

I guess your expectation is that the .csv would be set correctly in the filename?

**Comment by vindard** [comment]
> I guess your expectation is that the .csv would be set correctly in the filename?

Yes this
