### ISSUE TITLE
onchain receive improvment

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#2510]
1/
for lightning and onchain, invoice/address is in the top line
for paycode, lightning address is at the bottom line:
--> have all of them in the same place, I would suggestion bottom line (and maybe the single use could be switch to the top instead, altought I'm not sure of their usefulness, I would only keep the date)

2/  onchain address should be shown in full (instead of abc...def)

3/ copying onchain or lightning address show "`invoice` has been succesfully copied to clipboard"

**Comment by sandipndev** [comment]
Can you explain the last point?

**Comment by nicolasburtey** [comment]
> Can you explain the last point?

the toast that is been shown when copying the invoice. it always says invoice, even when it's not an invoice

**Comment by nicolasburtey** [comment]
another thing we apparently have missed: paycode/lightning address currently only work with the bitcoin wallet.
