### ISSUE TITLE
Send to BIP21 unified QR-Code always takes Onchain Address

### ISSUE THREAD

**Issue by pjw65** [GaloyMoney/galoy-mobile#2559]
Send to BIP21 unified QR-Code always takes Onchain Address, never Lightning.

See https://bitcoinqr.dev

**To Reproduce**
Paste or Scan unified QR Code (Onchain with Bolt 11)
bitcoin:BC1QYLH3U67J673H6Y6ALV70M0PL2YZ53TZHVXGG7U?amount=0.00001&label=sbddesign%3A%20For%20lunch%20Tuesday&message=For%20lunch%20Tuesday&lightning=LNBC10U1P3PJ257PP5YZTKWJCZ5FTL5LAXKAV23ZMZEKAW37ZK6KMV80PK4XAEV5QHTZ7QDPDWD3XGER9WD5KWM36YPRX7U3QD36KUCMGYP282ETNV3SHJCQZPGXQYZ5VQSP5USYC4LK9CHSFP53KVCNVQ456GANH60D89REYKDNGSMTJ6YW3NHVQ9QYYSSQJCEWM5CJWZ4A6RFJX77C490YCED6PEMK0UPKXHY89CMM7SCT66K8GNEANWYKZGDRWRFJE69H9U5U0W57RRCSYSAS7GADWMZXC8C6T0SPJAZUP6
or (Onchain with Bolt 12)
bitcoin:BC1QYLH3U67J673H6Y6ALV70M0PL2YZ53TZHVXGG7U?amount=0.00001&label=sbddesign%3A%20For%20lunch%20Tuesday&message=For%20lunch%20Tuesday&lightning=LNO1PG257ENXV4EZQCNEYPE82UM50YNHXGRWDAJX283QFWDPL28QQMC78YMLVHMXCSYWDK5WRJNJ36JRYG488QWLRNZYJCZS

Blink always takes the Onchain Address and I have to pay $2.50 for a bill of $7

**Expected behavior**
Default Lightning paymant with the option to take the Onchain.

Android 12
Blink Version 2.2.104.30000562

**Comment by nicolasburtey** [comment]
this should have been solved with the last released version. closing now but you can reopen if the issue persists
