### ISSUE TITLE
Allowing notifications triggers an error

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy-mobile#265]
**Describe the bug**
When notification permission is given an error is displayed in the app.

**To Reproduce**

1. Login
2. Go to receive bitcoin screen
3. Notification prompt is shown
4. Accept notification permission requests from os
5. See error

**Expected behavior**
No error should be displayed

**Comment by samerbuna** [comment]
This was working for me (to add device token) but we're disabling the notifications prompt for now until there are API operations to enable/disable notifications.

#296
