### ISSUE TITLE
Tapping notification menu item causes error

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy-mobile#266]
**Describe the bug**
When notifications have been allowed on the device we can modify whether they are allowed or not in the app settings using the menu item.  When clicking the menu item in settings an error is shown.

**To Reproduce**

1. Go to receive bitcoin screen
2. Accept all OS prompts to allow notifications
3. An error may be shown at this point... this is not the error this issue is about. Instead reload app if error is shown.
4. Go to settings menu
5. Tap notifications menu item
6. See error

**Expected behavior**
No error should be displayed

**Comment by samerbuna** [comment]
We're removing the Notifications menu item for now until it's supported in V2. #296
