### ISSUE TITLE
Currencies - SEK, NOK

### ISSUE THREAD

**Issue by agbegin** [GaloyMoney/galoy-mobile#2689]
User has requested following 

- Swedish Krona https://en.wikipedia.org/wiki/Swedish_krona
- Norwegian Krone https://en.wikipedia.org/wiki/Norwegian_krone

**Comment by vindard** [comment]
### Config
These are the settings I'm adding:
- `{ code: "NOK", symbol: "kr", name: "Norwegian krone", flag: "🇳🇴" }`
- `{ code: "SEK", symbol: "kr", name: "Swedish krona", flag: "🇸🇪" }`

---

### Rates
Sample rates from today (Nov 3) to show consistency we will have

**NOK**
- free-currency-rates-usd: `11.17113765`
  https://github.com/fawazahmed0/currency-api/blob/1/latest/currencies/usd/nok.json
- currency-beacon: `11.07383276`
  https://api.currencybeacon.com/v1/latest?base=USD&symbols=NOK&api_key=<your-key-here>

**SEK**
- free-currency-rates-usd: `11.06999857`
  https://github.com/fawazahmed0/currency-api/blob/1/latest/currencies/usd/sek.json
- currency-beacon: `10.92210246`
  https://api.currencybeacon.com/v1/latest?base=USD&symbols=SEK&api_key=<your-key-here>
