### ISSUE TITLE
App crashes after clicking scan button

### ISSUE THREAD

**Issue by ngutech21** [GaloyMoney/galoy-mobile#2697]
**Describe the bug**
The blink app crashes on iOS, if the user clicks on the scan-button on the home screen

**To Reproduce**
1. open the app
2. Click on scan-button on home screen
3. app crashes

**Expected behavior**
The app should open the camera view to scan a qr-code

**Smartphone (please complete the following information):**

- Device: iPhone 15 pro 1 TB (model A3102) 
- OS: iOS 17.0.2
- Blink version 2.2.140.589

**Additional context**
Bug is reproducible

**Comment by nicolasburtey** [comment]
does it crash every time systematically? 
did it offer to send the stack trace?

not able to reproduce the issue on my end

**Comment by ngutech21** [comment]
Yes the bug is reproducible. It crashes every time. 
IOS did not offer to send a stacktrace. Is there anything else I can add?

**Comment by nicolasburtey** [comment]
Are you loading the app in a particular way (self compilation or from our GitHub repo) or is it just from the App Store?

**Comment by ngutech21** [comment]
I installed the app from the App Store

**Comment by nicolasburtey** [comment]
next version will have an update camera library. maybe that'll solve the issue

**Comment by nicolasburtey** [comment]
can you try with version 2.2.159 @ngutech21 ?

**Comment by ngutech21** [comment]
With version 2.2.159 scanning of invoices works again on my iPhone. The app doesn‘t crash anymore.
