### ISSUE TITLE
Balance/transactions not updated when bitcoin is received

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy-mobile#272]
**Describe the bug**
If you are on the receiving end of a payment the app should refresh the transaction list and current balance.  Right now you need to pull down to refresh on the home page to trigger it.  When sending bitcoin the app automatically refetches the relevant queries so this behaviour should also take place after successfully receiving bitcoin.

**Comment by samerbuna** [comment]
Still need to test this but #296 should handle this.
