### ISSUE TITLE
Bad UX for onchain tx

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#2792]
When standing at a chivo ATM:
- No indication of how long to wait 
- no auto refresh of the tx once it's been sent to the mempool

**Comment by sandipndev** [comment]
For the indication of how long to wait, we need to include the estimated time that we get from bria.
https://github.com/GaloyMoney/bria/blob/49923cb0c39dcd6dba8d78c0802e50f1bc64fee8/proto/api/bria.proto#L359

This is coming out from SubmitPayoutResponse but in reality, this should be polled everytime the user asks for this information. Perhaps via caching.
cc @bodymindarts 

The auto refresh of tx can be done and I'm taking the task up.

**Comment by nicolasburtey** [comment]
`Payment has been sent successfully` screen should be worded different for onchain tx

**Comment by nicolasburtey** [comment]
this has been fixed
