### ISSUE TITLE
Argentina user account creation, prompt +549 phone extension 

### ISSUE THREAD

**Issue by agbegin** [GaloyMoney/galoy-mobile#2796]
When a user selects Argentina upon account creation phone number entry, let them know that a 9 may be required at the beginning of the user's phone number for them to receive the SMS. 

The 9 is added to represent a mobile phone [wikipedia](https://en.wikipedia.org/wiki/Telephone_numbers_in_Argentina#:~:text=The%20inbound%20dialing%20pattern%20for,54%209%20223%20123%E2%80%934567.)

**Comment by dolcalmi** [comment]
this is a nice to have not an issue

**Comment by UncleSamtoshi** [comment]
Addressed in PR https://github.com/GaloyMoney/galoy-mobile/pull/2798

**Comment by nicolasburtey** [comment]
closing this ticket. you can reopen if the issue persist @agbegin
