### ISSUE TITLE
Earn screen not scrollable after answering Quiz

### ISSUE THREAD

**Issue by pretyflaco** [GaloyMoney/galoy-mobile#2808]
![20231121_204033](https://github.com/GaloyMoney/galoy-mobile/assets/32958103/799de263-70a2-4551-bcde-678c814def92)

Lower part of screen is not legible after answering quiz. 

To reproduce: 

1 Go to a Quiz where the comment to an answer option is rather long

2 choose correct answer

3 answer is not fully on screen and cannot be revealed by scrolling (see screenshot)

**Comment by MaxwellDG** [comment]
I'll add a scrollview to that container

**Comment by MaxwellDG** [comment]
@nicolasburtey can close
