### ISSUE TITLE
Login header

### ISSUE THREAD

**Issue by MaxwellDG** [GaloyMoney/galoy-mobile#2812]
**Issue:**
Trying to log in with phone sends the user to the login screen with the wrong header. 

Pressing this:
![phone-login-1](https://github.com/GaloyMoney/galoy-mobile/assets/51105802/2a36498b-c3dd-49d6-8364-eb7c83070f40)

Goes to this:
![phone-login-2](https://github.com/GaloyMoney/galoy-mobile/assets/51105802/9834fddb-8297-4299-8b71-65930bf17367)

**Proposal**
Display a different header if the user is creating an account vs logging in with a phone number. I noticed from some unused code that this looked like the initial intention, and the latter scenario was intended to display the string 'Phone number'.

**Comment by sandipndev** [comment]
The header can just be renamed to "Authenticate" perhaps.
