### ISSUE TITLE
Blink Circles December Challenge

### ISSUE THREAD

**Issue by agbegin** [GaloyMoney/galoy-mobile#2818]
New challenge, for December: 

December Challenge!
Grow your inner circle by 10 people in December for a chance at $100!
To participate, share your circles on social once you’ve reached 10 for the month and tag #blinkcircles.
On January 1, three people will be chosen at random to receive $100.

<img width="349" alt="Screenshot 2023-11-23 at 6 50 50 AM" src="https://github.com/GaloyMoney/galoy-mobile/assets/90297599/6458346d-0343-4606-879e-c137cdc81fda">

Preview text: 
<img width="439" alt="Screenshot 2023-11-23 at 6 54 44 AM" src="https://github.com/GaloyMoney/galoy-mobile/assets/90297599/86e84e6a-b3f9-4dd3-bc42-088e95dddc2d">

December Challenge
+10 inner circle for a chance at $100!

**Comment by designsats** [comment]
ES:
¡Reto de diciembre!
¡Has crecer su círculo íntimo en 10 personas en diciembre para tener la oportunidad de ganar $100!
Para participar, comparte tus círculos en las redes sociales una vez que hayas llegado a 10 por mes y etiqueta #blinkcircles
¡El 1 de enero, se elegirán tres personas al azar para recibir $100!

¡Reto de diciembre!
"¡+10 a tu círculo interno para la oportunidad de ganar $100!"

**Comment by sandipndev** [comment]
@designsats can you add the ES translation to transifex?
