### ISSUE TITLE
Center map automatically at user location

### ISSUE THREAD

**Issue by designsats** [GaloyMoney/galoy-mobile#2830]
Im using map almost every time Im paying irl to a Blink user. Its much better experience to find business on the map, click "Pay this business" and fill the amount than scanning QR. Ive noticed few other people operating like this. 

**Problem**
Map is always centered at El Zonte and I need to click the icon to pan to my location. 

**Solution**
Cache the last map position or center it at user (whichever is easier to code)

**Comment by sandipndev** [comment]
We already ask for user's location when they open the maps tab. This would justify that request too.

**Comment by MaxwellDG** [comment]
I agree that'd be useful. I'll get on it
