### ISSUE TITLE
Transaction list screen visual design improvements

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy-mobile#284]
The transaction list screen has some visual quirks.  For instance the icon and the description are not vertically aligned.

**Comment by secondl1ght** [comment]
I noticed that the tx table looks fine on the home page, it only looks different on the contacts page. So we should be able to copy the styling over from the other transaction table.

**Comment by nicolasburtey** [comment]
I think those issues have been fixed. closing for now, we can reopen if there is more work to do
