### ISSUE TITLE
Fatal error on pressing 'Earns' tab

### ISSUE THREAD

**Issue by MaxwellDG** [GaloyMoney/galoy-mobile#2844]
![Screenshot from 2023-11-28 10-17-10](https://github.com/GaloyMoney/galoy-mobile/assets/51105802/fd9f316e-6874-4199-ba2a-3ea3a401e46c)

After navigating to the 'earns-map-screen.tsx' screen, a fatal error is shown. This causes the app to fallback to the default fallback error screen. 

Looks like this is being caused by the **ProgressBar** component. Might only be replicable when a section only has 1 quiz completed? Something along those lines.

@nicolasburtey I'll look into this ASAP. Also do you have a moment to discuss how the overall development process works for this project? Like is the main branch directly getting pipelined into production? You got a discord?

**Comment by nicolasburtey** [comment]
thanks!
