### ISSUE TITLE
Transactions are duplicated in transaction history screen

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy-mobile#285]
**Describe the bug**
In the transaction history screen it is sometimes displaying transactions as duplicated.

**To Reproduce**

1. Send/Receive some payments
2. Tap on transactions from Home Screen
3. View transaction history screen
4. See certain transactions are duplicated

**Expected behavior**
Transactions are displayed accurately.

**Screenshots**
![image](https://user-images.githubusercontent.com/3502409/140732836-30bbefd2-d9b9-49bc-bd4e-79bc7532249e.png)

**Additional context**
@nicolasburtey has suggested this might be related to pagination.

**Comment by daviroo** [comment]
Also transactions which are visible in the smaller transactions view in Home Screen are not always visible in the Transaction History screen.  Example shown below:

![image](https://user-images.githubusercontent.com/3502409/140733270-439c0bf8-1747-43a5-8066-4ba13efb9580.png)
![image](https://user-images.githubusercontent.com/3502409/140733304-cce06f7f-868e-452f-9b0c-cd11666b9d28.png)

**Comment by daviroo** [comment]
Also we currently can't pull down to refresh on the Transaction History screen so the only way to update this currently is to send bitcoin.

**Comment by samerbuna** [comment]
Fixed #295
