### ISSUE TITLE
Add secret + lightning invoice (payment request) in transaction details screen on payments out.

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy-mobile#286]
To help with support requests with payments we should include the secret and lightning invoice in the transaction details screen for sent payments.

**Comment by Aditi-Singh16** [comment]
Hi, I would like to work on this issue.

**Comment by nicolasburtey** [comment]
Hi @Aditi-Singh16 I think we want to return this as part of the mutation, so there are some backend work involved.

in case you are looking for a small issue to get started on our repo, this could be a good one: https://github.com/GaloyMoney/galoy-mobile/issues/1055

**Comment by nicolasburtey** [comment]
pre-image has been added. there is ticket already for adding the invoice
