### ISSUE TITLE
Receive Bitcoin screen does not update lightning payment request when adding a note

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy-mobile#287]
**Describe the bug**
Adding a note for a lightning invoice should update the payment request + QR code so that this can be forwarded to whoever is paying the invoice.

**To Reproduce**

1. Go to Receive Bitcoin screen
2. Change note field
3. See that payment request and QR code does not update
4. Scan QR code or copy payment request to another wallet and see that the note does not come over

**Expected behavior**
Changing the note field should update both the QR code and the payment request.

**Comment by samerbuna** [comment]
This seems to be working okay for me 🤔

**Comment by daviroo** [comment]
You're right I can't reproduce this.  Strange.  I'll close it for now and reopen if it pops up again.
