### ISSUE TITLE
queue info for onchain tx

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#2887]
- messaging not optimal (ie: shortly instead of now)
- need auto refresh in transaction detail page

**Comment by designsats** [comment]
Could we order the fields (50% opacity for inactive fields) in order of importance? 
- "transaction queued"
- destination
- fees
- account (no amount duplicity
- date 
- description
- type
- hash
- Cancel option (when possible)

![dark theme - transaction details](https://github.com/GaloyMoney/galoy-mobile/assets/17384787/2346ad2a-1193-4a76-80f3-703b8e5c6318)
