### ISSUE TITLE
2fa needed improvment

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#2913]
- need white border space on dark mode for QR code
 - entering incorrect code leads to be a 400 error code that is not very clear
 - other devices will be logged out when setting up totp

**Comment by sandipndev** [comment]
The first bullet is done in my UI PR

**Comment by nicolasburtey** [comment]
> The first bullet is done in my UI PR

awesome. thanks!

**Comment by nicolasburtey** [comment]
Closing this as 1. is pending on a PR and 2 and 3 have been addressed
