### ISSUE TITLE
Persist selected currency

### ISSUE THREAD

**Issue by samerbuna** [GaloyMoney/galoy-mobile#297]
Right now, when a user switches primary currency (to Sats) in send/receive screens, that change is persisted while the app is open. If the app is closed, that change is not cached and the app defaults back to USD. It would be great if we cache that.

I'm also wondering, if the primary currency is Sats, should we display the main balance in Sats first?

CC: @nicolasburtey

**Comment by nicolasburtey** [comment]
people in El Salvador thinks in dollar. so this should be the default currency for now I believe. I know it revert back to USD even if this has been changed in the settings. This is a acceptable behavior for now I believe (meaning: could be improved but this sounds to be a very minor issue compared to a lot of other items that are higher priority)
