### ISSUE TITLE
Add border to 2fa QR code for dark mode

### ISSUE THREAD

**Issue by jireva** [GaloyMoney/galoy-mobile#2972]
When the theme is set to dark mode, the QR code displayed in the 2fa setup screen doesn't scan because there is no border separating it from the black background.

**Smartphone (please complete the following information):**

- Device: iPhone6s
- OS: iOS 15.8
- Version: 2.2.210 (655)

**Comment by openoms** [comment]
Came here to report this. Same on Android. Switching to light mode make the QRcode readable.

**Comment by designsats** [comment]
I saw it in PR as already solved....is it?

**Comment by nicolasburtey** [comment]
@sandipndev has this in his PR but it's grown maybe a lot in scope and therefore has not been merged. Maybe @sandipndev it would be wise to cherry-pick the commit that fixes this.

**Comment by sandipndev** [comment]
Sure! I agree. There are similar bits in the PR which is not really related to failing E2E that can be made into a different PR. On it sir!
