### ISSUE TITLE
wait for intent before asking the user his geo localisation

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#2975]
with the recent PR, we are now asking for the geo localization of the user right when we tap on Map. I don't think that is the right behavior, because a user might want to see the map first, because saying "ok great, but who am I again on this map, and is there a merchant nearby that accepts bitcoin?"

so I think we should have a button or otherwise on top of the map to say "center to user location" and this is when we should ask the user for permission. maybe @designsats have some idea on this?

Note: at least this is the behavior on iOS. not too sure if Android is the same.

**Comment by nicolasburtey** [comment]
related, we need to update the config file on iOS:

```
We identified one or more issues with a recent delivery for your app, "Blink (Bitcoin Beach Wallet)" 2.2.212 (657). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “Blink.app” bundle should contain a NSLocationAlwaysAndWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.
```

**Comment by designsats** [comment]
Thats how it currently works on Android. There is a button that centers the map. So something like that for IOS too but with remembering the last position.

**Comment by MaxwellDG** [comment]
> NSLocationAlwaysAndWhenInUseUsageDescription

This is the weird one I was mentioning before. We don't actually use this, and it can be explicitly disabled. But the docs require it nonetheless. Even though the app works without it. And it's the more invasive location request too. I'll see if anyone's gotten around that without having to ask for it.

**Comment by MaxwellDG** [comment]
> with the recent PR, we are now asking for the geo localization of the user right when we tap on Map. I don't think that is the right behavior, because a user might want to see the map first, because saying "ok great, but who am I again on this map, and is there a merchant nearby that accepts bitcoin?"
> 
> so I think we should have a button or otherwise on top of the map to say "center to user location" and this is when we should ask the user for permission. maybe @designsats have some idea on this?
> 
> Note: at least this is the behavior on iOS. not too sure if Android is the same.

I should add that this feature was added due to the request of #2830. What @nicolasburtey is requesting here is very different than what @designsats was requesting. So I think we've gotta chat and agree upon a final idea.

**Comment by designsats** [comment]
Im okay to tap the button to localize me at first, but subsequent openning of the map should be where I left it. BTCmap behaves like this.

**Comment by MaxwellDG** [comment]
> Im okay to tap the button to localize me at first, but subsequent openning of the map should be where I left it. BTCmap behaves like this.

The solution you're proposing would be helpful with permissions as well. We could completely remove the Geolocation library and the main point of this issue (Apple requesting the invasive "NSLocationAlwaysAndWhenInUseUsageDescription") would be voided. We'd use local caching instead to keep the most previous coords.

I should add though that I'm still not in love with the solution yet. It's confusing to open a map and always be a little bit off of your location from last time. Maybe if I make the 'focus on user location' button more clear then it'd be better? Could add some text that says "Focus on location"

**Comment by MaxwellDG** [comment]
wait wait wait. I have an idea. Might be able to get rid of Geolocation library (and the additional permission) and do everything we want with just react-native-maps library. I'll write it tomorrow evening.

**Comment by MaxwellDG** [comment]
@nicolasburtey @designsats Alright I found a way to get this done without the extra permission request. But I'll need all of us in agreement on this proposal before I rewrite it.

I can render a quick MapView without any Markers and then put a complete overlay on top of it. The user will only see this loading screen overlay, and it'll be for like 2 seconds. During that screen, the app will ask for 1 location permission (the same one it always has). If the user accepts, then I'll create a new MapView with all the markers and remove the overlay. And this will start centred on the user's location. 

**Pros**: 
- removes the need for the extra invasive permission
- can remove the whole Geolocation library
- starts exactly at the user's location every time if they say yes. saying no will resort to their ip's country

**Cons**
- this will require a couple seconds loading screen overlay (could have a progress bar and some pictures so its less ugly)
- Nicholas doesn't get his button to prompt for permissions. It'll be asked automatically
