### ISSUE TITLE
Earn section – chapter 1 is locked for new users 

### ISSUE THREAD

**Issue by agbegin** [GaloyMoney/galoy-mobile#2996]
Many users are reporting an issue where they're seeing the "Not yet. This chapter will be available tomorrow" before they're able to complete any lessons. 

Some users even seeing "Error. Quiz question was already claimed." When they had not earned any sats yet. 

Multiple different phones, across android and iPhone. Unsure of version numbers, but these are all newly downloaded users (Jan 7-8), most likely 2.2.209

<img width="774" alt="Screenshot 2024-01-09 at 9 38 23 AM" src="https://github.com/GaloyMoney/galoy-mobile/assets/90297599/d1f24f44-8105-428e-94ec-096a830310f2">

**Comment by nicolasburtey** [comment]
I think this is fixed and been rolled out. closing but can reopen if problem persists
