### ISSUE TITLE
misleading message when price is out of date

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#301]
We need to improve the flow when the price is not up to date:
- restarting the app should not be the action. maybe going back to the previous screen?
- also we should investigate why this issue is hapening in the first place. Justin B looked at it but didn't find the root cause.
- error text is also incredibly small

![image](https://user-images.githubusercontent.com/11156370/142737850-70f908ca-6934-4e74-b628-1f3cdcf6d315.png)

![signal-2021-11-20-115723](https://user-images.githubusercontent.com/11156370/142737836-c69f2c6c-ce5c-45c8-86d2-a3c58e35d3c7.png)

**Comment by samerbuna** [comment]
David and I actually removed this warning when we switched to updates via subscription, but let's repurpose this issue to track what we need to do in the UI when the subscription connection fails. It's now not just the price, but balance and transactions too. I think we should display a global message with button to refresh the app.

**Comment by daviroo** [comment]
I guess it would depend on why the subscription failed.  If we are returning errors from the server then we would want to display a different error.  In the event that there is no network then something along the lines of "Please restore network connection before making a payment".
