### ISSUE TITLE
Pixel Camera Services keeps stopping on GrapheneOS

### ISSUE THREAD

**Issue by openoms** [GaloyMoney/galoy-mobile#3044]
**Describe the bug**
Every time Blink is opened there is an error with the camera. Everything works afterwards. The camera also works in Blink and other apps. There are no similar errors using other apps.

**To Reproduce**
Open Blink when it is not in the background already.
In the error popup click `Close app`
Carey on using Blink as normal

**Expected behavior**
No error on opening.

**Screenshots**
![IMG_20240205_220842](https://github.com/GaloyMoney/galoy-mobile/assets/43343391/ee1308c8-2885-4c71-a36e-68f6bd5c3c4c)

**Smartphone (please complete the following information):**

- Device: Pixel 5
- OS: GrapheneOS - (Android 14)
- Version: 2.2.226

**Comment by nicolasburtey** [comment]
is this a new bug? or what the behavior the same in the previous version? (we upgrade the camera library in the last version)

**Comment by openoms** [comment]
It is fairly new ~ 2weeks, but can't recall exactly if it started after a GrapheneOS update.
I did not report it first hoping another OS update will fix it, but it persists now after another GrapheneOS update.

Downgraded Blink to 2.2.221 to before the camera library update and the problem is still there when logged in the app.

Curious if anyone else is experiencing the same? @agbegin do you have that GrapheneOS phone still?

**Comment by openoms** [comment]
The error message went away when updating to the prerelease version v2.2.228 so closing.
