### ISSUE TITLE
Pass invoice to Blink from apps

### ISSUE THREAD

**Issue by agbegin** [GaloyMoney/galoy-mobile#3045]
Multiple reports of Blink not receiving the invoice from other apps, for nostr zapping as well as for bitrefill payment. 

To replicate: 
- Open bitrefill
- Put item in cart, tap checkout
- Select pay with Lightning
- Select Blink
- Tap "Open in Blink"
- See empty address field
- Try again with Muun, the destination is autopopulated (expected behavior)

**Comment by UncleSamtoshi** [comment]
Fix in #3047
