### ISSUE TITLE
Right to left send payment bug

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#3055]
![image](https://github.com/GaloyMoney/galoy-mobile/assets/11156370/797efe4e-4752-4633-b6e2-f7528d148dd0)

**Comment by nicolasburtey** [comment]
tried to use the app in Arabic and could not reproduce.

**Comment by nicolasburtey** [comment]
OS settings needs to be in Arabic too

**Comment by nicolasburtey** [comment]
can't really reproduce but we have more people reaching out who have the bugs

**Comment by Prakhar-Agarwal-byte** [comment]
I would like to work in this issue

**Comment by nicolasburtey** [comment]
> I would like to work on this issue

go ahead!
