### ISSUE TITLE
Add Polish Złoty currency to Blink

### ISSUE THREAD

**Issue by jesterhodl** [GaloyMoney/galoy-mobile#3069]
**Is your feature request related to a problem? Please describe.**
As a user, I was unable to select Polish Złoty (PLN) as my currency in order to create an invoice value denominated in my local currency to settle a transaction with my mates.

**Describe the solution you'd like**
I would love to be able to select **PLN - Polish Złoty - 🇵🇱**
That should enable me to set amounts when e.g. receiving invoices

**Describe alternatives you've considered**
Converting PLN to USD outside of the app

**Additional context**
So listing a currency and exchange rate is one thing.
Another is formatting in other places of the UI.
The official currency format for poland is
9 999 999,99 zł

space as thousands separator
, as decimal separator
2 decimal places
currency name on RHS after a space.
zł is the local currency name
PLN is often used in international context as it is the official international code

**Comment by itstomekk** [comment]
I also would love to see PLN in Blink

**Comment by dolcalmi** [comment]
PLN has been added, please let us know if you find any problems

**Comment by jesterhodl** [comment]
Looks good, but the transaction history seems to show historical currency, see below.

I suppose that is another topic.

Other places look ok, thank you very much!

![image](https://github.com/GaloyMoney/galoy-mobile/assets/103882255/47cf09c4-d14d-4c3b-8a66-f2148e220e42)

**Comment by nicolasburtey** [comment]
It's by design that historical transaction have the currency you used at the time

**Comment by jesterhodl** [comment]
ok, thanks! 👍
