### ISSUE TITLE
Bolt card balance check with NFC

### ISSUE THREAD

**Issue by openoms** [GaloyMoney/galoy-mobile#3071]
Bolt cards need to have some kind of solution to check the balance without logging in to the funding account.
Tapping a bolt card to a wallet which does not require a defined amount first (like WoS) shows the max withdrawable balance.
Cannot do this with Blink as we require to set an amount before reading the NFC. Could this be relaxed? The NFC flow would be faster and the wallet could display a from - to withdrawable amount.
Should be set to 0 by default (not to max as in WoS) to avoid accidental large withdraws.

In other systems (as in LNBbits I know) you can set a max payment size also.
If the max payment size is smaller than the balance on the card it would just show the limit as the max withdrawable amount.
Might not be a problem just need to note that the max number is a payment limit, the balance could be higher.

tagging @rockstardev for additional context

**Comment by nicolasburtey** [comment]
the feedback I got was that it's not advisable to tell the balance of a boltcard to a POS device. if it's about setting a lower withdrawable amount, than I'm not sure what would be the point of activating this feature?

this is a tradeoff on the security / privacy to convenience. I generally think that it's not ideal to expose the balance to the POS. for instance, no such card POS would give you the balance of the card owner. And that is probably better as is.

**Comment by openoms** [comment]
Agree that this balance check shouldn't even be possible so it is not a good use case. Thank you for the input, closing.
