### ISSUE TITLE
March Blink Circles Challenge 

### ISSUE THREAD

**Issue by rudyblink** [GaloyMoney/galoy-mobile#3073]
### New content for modal 

--ENGLISH--
March Challenge!

Grow your Inner Circle by 3 and your Outer Circle by 3 for a chance at winning $100

Reminder: your circles grow when you send a new Blink user their first sats.

Share your circles on social with #blinkcircles to participate

--SPANISH--
Reto de marzo!

Aumenta tu círculo interno en 3 y tu círculo externo en 3 para tener chances de ganar $100.

Recordatorio: Tus círculos crecen cuando envías a un nuevo usuario de Blink sus primeros sats.

Comparte tus círculos en las redes sociales con el hashtag #blinkcircles para participar.

### New content for the card on the circles dashboard that opens the modal

--ENGLISH--
March Challenge!
3 inner circle and 3 outer circle for a chance to win $100

--SPANISH--
¡Reto de Marzo!
3 en tu círculo interno y 3 en tu círculo externo para tener la oportunidad de ganar $100

![Frame 10002](https://github.com/GaloyMoney/galoy-mobile/assets/156244225/3f04fe6f-e89a-41b7-99ce-04271a7450fd)

**Comment by pretyflaco** [comment]
> for a chance at winning $100

Thoughts on the following modification? 

for a chance at winning $100 OR two tickets to [Adopting Bitcoin Arnhem in Netherlands](https://adoptingbitcoinarnhem.com)

**Comment by rudyblink** [comment]
Interesting!

As far as I understand we don't serve Europe and a lot of our Circles
participants are form Latam and Africa, so I'm not sure if it's a deal for
them. Wyt?
