### ISSUE TITLE
Missing translation in confirmation screen

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy-mobile#311]
**Describe the bug**
Back needs to be translated

**To Reproduce**

1. Change the Language to spanish (Settings screen)
2. Go to send screen and try to send for ex an intra ledger tx
3. In confirmation screen you will see the back button without translation

**Expected behavior**
Back should be translated (common.back key)

**Screenshots**

![photo4970265859104811482](https://user-images.githubusercontent.com/2079600/143476969-e7c99585-4a84-42b5-a57d-4ff4dd2d2564.jpg)
**Smartphone (please complete the following information):**

- Device: iPhone Xs
- OS: iOS 15.1
- Version 1.6.0 283

**Comment by daviroo** [comment]
I'm not able to reproduce this @dolcalmi.  This is what I see when I carry out the same steps:
![image](https://user-images.githubusercontent.com/3502409/143686710-f31102b7-2612-443c-872c-7ee532c7d49d.png)

**Comment by samerbuna** [comment]
react-navigation uses the previous-screen name if there's available space, otherwise it uses "Back". I don't see a way to customize that "Back" generically though. It can be customized per screen using [headerBackTitle](https://reactnavigation.org/docs/native-stack-navigator/#headerbacktitle).

**Comment by dolcalmi** [comment]
> I'm not able to reproduce this @dolcalmi. This is what I see when I carry out the same steps:

try with intraledger `user0` or `user11` in staging

**Comment by daviroo** [comment]
> react-navigation uses the previous-screen name if there's available space, otherwise it uses "Back". I don't see a way to customize that "Back" generically though. It can be customized per screen using [headerBackTitle](https://reactnavigation.org/docs/native-stack-navigator/#headerbacktitle). 
> 
> 
> 
> 

Thanks @samerbuna .  I guessed it would be something like that but I wasn't sure on the exact way it worked. In that case I think we should always override the 'headerBackTitle' with a translation.
