### ISSUE TITLE
Camera inside Blink App fails to read Phoenix Ln invoice (displayed on iPhone with medium high brightness)

### ISSUE THREAD

**Issue by jm9151821** [GaloyMoney/galoy-mobile#3125]
**Describe the bug**
Attempting to scan a phoenix ln invoice displayed on an iphone SE 2nd gen with medium-high brightness the camera from a Redmi A2 fails to focus appropriately to scan the QR code. (as I write this I found a fix, lower the screen brightness on the iphone and then camera inside Blink app is able to focus and read the phoenix ln invoice) However, if I use the normal phone camera  app from the Redmi A2 it successfully is able to focus on phoenix ln invoice on iphone with medium-high brightness.

**To Reproduce**

1. Go to Scan QR code using a Redmi A2 
2. See Camera unable to focus in on the ln invoice displayed on iphone with medium-high brightness

**Expected behavior**
The phoenix ln invoice should be easily read inside Blink. 

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Redmi A2
- OS: Android 
- Version Go Edition 13

**Additional context**
Another camera related [Issue 3113](https://github.com/GaloyMoney/galoy-mobile/issues/3113 )

**Comment by nicolasburtey** [comment]
closing after discussing with @jm9151821
