### ISSUE TITLE
Add LNURL integration

### ISSUE THREAD

**Issue by krtk6160** [GaloyMoney/galoy-mobile#316]
## Title
Add [LNURL](https://github.com/fiatjaf/lnurl-rfc/blob/legacy/lnurl-pay.md) and [Lightning address](https://github.com/andrerfneves/lightning-address) integration

## Description
From #63 :

> currently payment in the form of [lnurl-pay](https://github.com/fiatjaf/lnurl-rfc/blob/master/lnurl-pay.md) are not accepted by the mobile application.
> 
> lnurl-pay is very useful in the context of printed QR code, such that a merchant could have a printed QR code and their customer could pay by simply scanning the QR code, whether they use the Galoy wallet or [any other wallets](https://github.com/fiatjaf/awesome-lnurl#wallets) that accept lnurl-pay.
> 
> Eventually we want to work on lnurl with our own platform, but on the mobile side, the task can be developped independantly by using other platforms. a good way to test this is to use [this messaging platform](https://chat.blixtwallet.com/).
> 
> on scanning the QR code from https://chat.blixtwallet.com/, our wallet should ask for the invoice, have a screen for confirmation and then pay it.
> 
> BlueWallet has a [complete integration of lnurl](https://github.com/BlueWallet/BlueWallet/search?q=lnurl) so looking at their repo is a good way to understand the whole flow.

| Date added    | Bounty Amount |
|---------------|---------------|
| 23/11/2021    | 0.03 BTC |

**Comment by pseudozach** [comment]
hi, I'm attempting this bounty, will update here with progress.

**Comment by pseudozach** [comment]
I pushed the code, pending review/feedback: https://github.com/GaloyMoney/galoy-mobile/pull/321

**Comment by krsjoseph** [comment]
Is this bounty still open, or is it closed?

**Comment by pretyflaco** [comment]
Can this issue be closed? Afaik, LNURL-Pay has been merged. Or we keeping this open for LNURL-withdraw etc?
