### ISSUE TITLE
Blink Circles Bug

### ISSUE THREAD

**Issue by rudyblink** [GaloyMoney/galoy-mobile#3160]
**Describe the bug**
People are seeing their circles not update in realtime or seeing them reduce instead of increase when onboarding

**To Reproduce**
1. Send a new Blink user their first sats
2. Click on "View my Circles"
3. Check if your Circles counter is less than before or it's not updated. 

**Expected behavior**
After onboarding a new Blink user you should see your inner Circle get bigger

**Smartphone (please complete the following information):**

- Device: iPhone 13
- OS: IOS 17.3.1
- Version 2.2.239.683

**Comment by jm9151821** [comment]
+1 real time is not happening anymore. It seems its waiting for a midnight time. It refreshes the next day after onboarding a person.

**Comment by openoms** [comment]
@jm9151821 @rudyblink please check again when you are onboarding someone. This should be fixed.

**Comment by nicolasburtey** [comment]
closing for now. you can reopen if the issue has not been fixed
