### ISSUE TITLE
Contacts not updating

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy-mobile#327]
**Describe the bug**
Contacts are not updating in the app after a successful payment has been made using a username

**To Reproduce**

1. Send a payment to someone who isn't already a contact using their username
2. Navigate to contacts screen and notice that their username hasn't been added as a contact

**Expected behavior**
When successful payments are made to a username that username should be added to your list of contacts

**Comment by vindard** [comment]
I observed this as well with 3 payments I did in Zonte last week. The 1st and 3rd payments didn't update but the 2nd one did. I can confirm this isn't a backend issue as well and report back here.
