### ISSUE TITLE
On-chain payment with wrong description

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy-mobile#332]
**Describe the bug**
On-chain payments description is showing `OnChain Receipt`

**To Reproduce**

1. Send an On-chain payment
2. Go to Transaction history or payment detail
3. Transaction description shows "OnChain Receipt"

**Expected behavior**
Description should show the note or "OnChain Payment" (please check with @samerbuna or @nicolasburtey )

**Screenshots**

![photo5006282600150575586](https://user-images.githubusercontent.com/2079600/145089259-db3f800c-c55f-464a-a531-1caa1620a7b7.jpg)

**Smartphone (please complete the following information):**

- Device: iPhone Xs
- OS: iOS 15.1
- Version 1.6.0 build 290

**Comment by daviroo** [comment]
@samerbuna @nicolasburtey do you have any feedback on @dolcalmi's suggestion?  Should description show the note or "OnChain Payment"?

**Comment by samerbuna** [comment]
@daviroo yeah, I think "OnChain Payment" is better

**Comment by daviroo** [comment]
@dolcalmi informed me that I haven't taken into account the direction of the payment in this change so I have reopened it.

**Comment by daviroo** [comment]
@dolcalmi I spoke with @samerbuna about this and he agrees that showing the same description for both send and receive is fine.  Do you mind if I close this issue or do you want to discuss further?
