### ISSUE TITLE
Missing text in security and phone code screens

### ISSUE THREAD

**Issue by krtk6160** [GaloyMoney/galoy-mobile#334]
**Describe the bug**
Some text is missing from the security and phone code screens. For the latter, it is the dropdown label that's missing.

**Screenshots**

![Screenshot_20211208-021345_Bitcoin Beach.jpg](https://user-images.githubusercontent.com/17320781/145112696-cc1bf3ff-22e8-4d3c-9e56-e46316d12390.jpg)
![Screenshot_20211208-021447_Bitcoin Beach.jpg](https://user-images.githubusercontent.com/17320781/145112710-dc261143-92ea-430b-847f-9ebb8c236d3b.jpg)

**Smartphone (please complete the following information):**
- Device: Galaxy S21
- OS: Android 12
- Version: 1.6.0 build 291

**Comment by daviroo** [comment]
I raised #336 to partially fix this.  We have another PR open to change the library we are using in the phone auth screen input in #324.  I think we should try and get that merged as that will most likely also fix the other issue.
