### ISSUE TITLE
Contacts detail screen is unusable on certain devices

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy-mobile#355]
**Describe the bug**
On devices with a small screen the contacts detail screen is unusable.  See example below.

![image](https://user-images.githubusercontent.com/3502409/146175051-c74a0b66-7c03-431f-9342-99d07c78397f.png)

We should probably reduce the size of the top part of the screen which we currently use for updating the alias.

**Comment by secondl1ght** [comment]
I submitted a PR to fix this #404
