### ISSUE TITLE
make sure phone only have + and number

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#37]
phone number form when logging in case have non number characters like ",". the query is still send to the backend but is being rejected. there should be a check before sending the query that the phone number has the same regex check than the backend has.

**Comment by dannyjmac** [comment]
[PR 76 ](https://github.com/GaloyMoney/galoy-mobile/pull/76)

**Comment by daviroo** [comment]
Looks like this was fixed in #76.
