### ISSUE TITLE
Transactions History view doesn't refresh properly

### ISSUE THREAD

**Issue by vindard** [GaloyMoney/galoy-mobile#379]
**Describe the bug**
The Transactions History page doesn't refresh on pull down for new payments received.

**To Reproduce**

1. Open the app to the Transactions History page in the app
2. Send a payment outside the app (e.g. via api directly)
3. Pull down from top on the Transactions History page, see no change
4. Go back to home screen and pull down, see new payment come in in little Transactions window
5. Go back to Transactions History page and see new payment now show up.

**Expected behavior**
New transactions should appear on refresh from the Transactions History view.

**Smartphone**

- Device: OnePlus9
- OS: Android

**Comment by nicolasburtey** [comment]
This should have been addressed with the last version of the app
