### ISSUE TITLE
Login request sent twice

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy-mobile#398]
**Describe the bug**
Mobile app is sending twice the login request. We found it because we are having a race condition in the backend. 

Query with all the users with errors
https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/j9YKLtSV41d

Ex: https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/A8yMEANg4zL?tab=traces (you can verify requests with a milisecs diff)

**Comment by nicolasburtey** [comment]
Closing, assuming the issue is no longer present. Please reopen if that's not the case
