### ISSUE TITLE
Earn sats screens text and background contrast too low

### ISSUE THREAD

**Issue by secondl1ght** [GaloyMoney/galoy-mobile#400]
I have noticed on some devices the contrast between the background color and text color on the Earn Sats screens is too low, making it very difficult to read the text on the screen. My suggestion would be to change the text color from a gray shade to solid black, what do you guys think of this? If everyone agrees I can put in a PR for this change.
It looks good on the emulator here but I tested it on a actual device and could not read very well.
![image](https://user-images.githubusercontent.com/85003930/155784311-9c2624d4-c0ba-43f7-bf4a-e49af3ffeb33.png)

**Comment by 55thParallelNorth** [comment]
I agree, I downloaded the app to use on Bitcoin Beach for my travels and it is very hard to read. I have attached a screenshot. 
![Uploading Screenshot_20220305-104312_Bitcoin Beach.jpg…]()

**Comment by nicolasburtey** [comment]
This has been fixed
