### ISSUE TITLE
En Bitcoinbeach Wallet no funcionan el pago de hold invoice en LN

### ISSUE THREAD

**Issue by soyishikawa** [GaloyMoney/galoy-mobile#409]
Saludos, 
Soy un usuario de El Salvador, me he interesado por comprar Bitcoin vía P2P, hay un bot Lightning de Telegram genial, llamado lnp2pBot con el cual se puede comprar en el Salvador, resulta que lo probé, generando un invoice de LN desde Bitcoinbeach Wallet, pero No me fue posible, probé desde Moom wallet, Blue wallet y si me dejó, el problema con Bitcoinbeach Wallet es que no funcionan el pago de hold invoice, si pudiera agregar esa funcionalidad o feature sería genial.mas aportunidades para los Salvadoreños. Gracias.

**Comment by grunch** [comment]
Hey @SoyIshiKawa  I just tested Bitcoin beach wallet on buying and selling with @lnp2pbot and it works perfect, it handles hold invoices right on settled and cancelled invoices, I think this issue can be closed unless you have something else to add.
