### ISSUE TITLE
Mobile app in Portuguese - Translation Ready!

### ISSUE THREAD

**Issue by motolese** [GaloyMoney/galoy-mobile#414]
Here is my contribution to the Bitcoin Beach Wallet:
The JSON file with everything translated to Brazilian Portuguese
**https://github.com/motolese/galoy-mobile-ptbr/blob/main/pt-br.json**

I hope it works and be included in the next release.
Some improvements are needed!

**Comment by daviroo** [comment]
Hey @motolese.  Thanks for the contribution.  There is a back end change necessary before we can merge this change.  I'll speak to the rest of the team and get back to you once I know exactly what is required to give you an idea of how long it will take.

**Comment by nicolasburtey** [comment]
can't this be integrated even if there are changes to do in the backend @daviroo?

**Comment by daviroo** [comment]
> can't this be integrated even if there are changes to do in the backend @daviroo?

We can merge the file provided actually.  There will be follow up work to do to actually expose this as an option in the app (after we have made the server side change).

**Comment by daviroo** [comment]
The translation file you provided has been merged @motolese.  As I stated above there is some additional work to be done before the user can select this language - will leave this issue open until it is actually available to users.

**Comment by motolese** [comment]
Nice... I will be waiting for it.
Thank you!

**Comment by nicolasburtey** [comment]
Language has been added. @motolese  feel free to ask to join our transigez if you're not already there
