### ISSUE TITLE
Add LNURL-withdraw Support

### ISSUE THREAD

**Issue by leesalminen** [GaloyMoney/galoy-mobile#415]
**Is your feature request related to a problem? Please describe.**

Bitcoin Jungle has some General Bytes BATMs that require a wallet to support LNURL-withdraw in order to buy bitcoin over lightning.

**Describe the solution you'd like**

When scanning a LNURL-withdraw QR code, it should allow the user to receive bitcoin over lightning.

**Additional context**
We've written some code for this and is currently in testing. Wondering if Galoy would be interested in a PR for this?

**Comment by nicolasburtey** [comment]
> We've written some code for this and is currently in testing. Wondering if Galoy would be interested in a PR for this?

definitively. is it mobile only or do we need to change something on the backend as well?

**Comment by openoms** [comment]
+1 to be able to receive by scanning an LNURLw string.

On the other hand being able to generate an LNURLw string would allow paying with the link while offline.
It can be loaded to an NFC sticker or card as well for contactless support or just support offline usage of the wallet app.

**Comment by pretyflaco** [comment]
Turned this feature request into a [bounty](https://github.com/GaloyMoney/galoy/discussions/1417)!

**Comment by nicolasburtey** [comment]
this has been implemented
