### ISSUE TITLE
Running locally on Mac M1 - Gradle Issue?

### ISSUE THREAD

**Issue by LAMike310** [GaloyMoney/galoy-mobile#42]
**Describe the bug**

After cloning the repo and installing the dependencies, I got an error running `react-native run-android`

I downloaded Android Studio, and Java 13 with OpenJDK

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'GaloyApp'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not create service of type OutputFilesRepository using ExecutionGradleServices.createOutputFilesRepository().
      > Timeout waiting to lock Build Output Cleanup Cache (/Volumes/SSD/Code/galoy-mobile/android/.gradle/buildOutputCleanup). It is currently in use by another Gradle instance.

```
**To Reproduce**
1. Clone Repo
2. Install & Configure Android Studio
3. Download Java 13
4. Download Android emulator
5. `yarn` install
6. `react-native run-android`

**Expected behavior**

Open the Android emulator

Is anyone developing on a M1 Mac? I think that might be at the root of the problem, Java not playing nice with the M1 chip. Any help would be appreciated!

**Comment by nicolasburtey** [comment]
I'm on a Mac but pre M1.

someone reach out yesterday and had issue compiling the app. he seems the issue was resolved by having another java version. don't have the detail but that could be something to look for. 

if we rely on specific java version (not aware but that could really be possible) we should obviously update the doc or try to get rid of this dependency

**Comment by jrbuhl93** [comment]
I was able to get Android built on an M1 mac with Java 8 and OpenJDK.

**Comment by nicolasburtey** [comment]
I think this is resolved now
