### ISSUE TITLE
White text on payment timeout screen

### ISSUE THREAD

**Issue by vindard** [GaloyMoney/galoy-mobile#427]
## Description

Our usual "white text" issue, this time on payment timeout screen

![image](https://user-images.githubusercontent.com/17693119/162853511-37553ca1-d10c-4798-9e5d-038f71abe3de.png)

**Comment by daviroo** [comment]
This screen will be rewritten during the USD integration work.  I've been trying to ensure that all fonts have an explicit colour while doing this work.  I'll keep the issue open for now but we can probably close it after USD work has been merged.
