### ISSUE TITLE
add whatsapp phone number for support in the mobile wallet

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#44]
**Is your feature request related to a problem? Please describe.**
People who want to reach out for any question on the wallet don't know how to do it.

**Describe the solution you'd like**
There is no easy way to contact the support from the app currently. The easiest way to get started because we think of a broader approach is to add a button from the settings to open the whatsapp app when tapping on a button.

The number can be hardcoded for now. We could provide the number with an API through the backend in later update. 

**Describe alternatives you've considered**
In app messaging, but would take a long time to implement

**Additional context**

**Comment by cryptosalomao** [comment]
Addressed in #45
