### ISSUE TITLE
improve phone number formatting on confirmation screen

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#46]
**Is your feature request related to a problem? Please describe.**
When confirming the code sent by text, there is no mention of which phone the code was sent to.
This is from the prior screen. So if the phone was not entered correctly the only way to figure out is typically to wait for a few minutes, and if nothing happen go the previous screen

**Describe the solution you'd like**
Show the phone code in the code confirmation page.

**Comment by nicolasburtey** [comment]
https://github.com/GaloyMoney/galoy-mobile/pull/48 is a first step. the downside is that the phone number is presented with the international prefix. many people who have not lived abroad might not be aware that +503 is supposed to be the international prefix and could be confuse by that.

I'll confirm this is the case when I'll be physically in El Salvador.

**Comment by nicolasburtey** [comment]
@daviroo

**Comment by secondl1ght** [comment]
It looks like the phone number is displayed now so I think we can close this issue.
