### ISSUE TITLE
Lnurl is not being decoded for fee probe

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy-mobile#493]
**Describe the bug**
v 2.0.3-321 is sending a lnurl string to lnNoAmountInvoiceFeeProbe

**To Reproduce**
I dont have this version but you can check the trace https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/bwGh7oaP4eX/trace/c7R3jDDTVbP?fields[]=name&fields[]=service.name&span=a33945045b0d010b

Header values in HTTP POST span

**Expected behavior**
- detect and decode lnurl
- request a valid invoice
- send a valid invoice to  lnNoAmountInvoiceFeeProbe

**Smartphone (please complete the following information):**

- Device: ??
- OS:Android
- Version: 2.0.3-321

**Comment by nicolasburtey** [comment]
code has been rewritten on this. we can reopen another issue if the problem is still present
