### ISSUE TITLE
Sats amount should not change for invoices with amount

### ISSUE THREAD

**Issue by dolcalmi** [GaloyMoney/galoy-mobile#558]
**Describe the bug**
When you read a QR (lightning or on-chain) with specific amount the amount in sats sometimes change because price changes and because default currency is usd.

**To Reproduce**

1. Scan a QR with an invoice or on-chain address with specific amount
2. Click on Next
3. Wait for price changes
4. See sats amount change 

**Expected behavior**
When we read an invoice or an on-chain qr with specific amount the amount in sats should be fixed. This is specially important for on-chain because invoice behavior will be handled by the backend (with the payment request)

**Smartphone (please complete the following information):**

- Device: iPhone Xs
- OS:iOS 15.5
- Version v2.0.13 build 327

**Comment by vindard** [comment]
I've been meaning to file this issue as well. I made a video showing the issue

https://user-images.githubusercontent.com/17693119/178311506-d3520529-2298-4a84-815a-df5b2aed5720.mp4

**Comment by nicolasburtey** [comment]
I'm assuming this one has been fixed, but we can open if that's not the case
