### ISSUE TITLE
add a "do you like the app? you can review"

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#6]

**Comment by daviroo** [comment]
@nicolasburtey mentioned in a separate chat that we should add this to increase our ratings in the app store.  We should probably look to gain feedback when the user has completed an important action e.g. made a successful transaction. I found a good blog post which talks about [collecting user feedback](https://www.reactnativeschool.com/best-practices-for-capturing-user-feedback-in-react-native) and I also found a library which ties into the native android/ios rating systems called [react-native-rate](https://www.npmjs.com/package/react-native-rate).

**Comment by jrbuhl93** [comment]
The flow I had in my last app was

1. Asking the user if they are enjoying the app.

If yes:

2. Ask if they want to review.
3. If yes, prompt for a review.

If no:
2. Ask if they need help from support.
3. If yes, bring them to support.

**Comment by pretyflaco** [comment]
This feature request has now a bounty on it. [More info here](https://github.com/GaloyMoney/galoy/discussions/1362)

**Comment by abhiShandy** [comment]
I'm interested in solving this issue.
