### ISSUE TITLE
better permission for iOS

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#60]
**Is your feature request related to a problem? Please describe.**
We should not request to find and connect decives to the local network at app startup, this is not a good UX practice.

**Describe the solution you'd like**
maybe there is some features we use that would use that "local network" request (I'm not sure, to be investigated). in that case we should request this in context, whenever it's needed

![Uploading IMG_5492.PNG…]()

**Comment by jrbuhl93** [comment]
@nicolasburtey Could you upload the image associated with this issue again?
