### ISSUE TITLE
LNURL QR scan not populating amount

### ISSUE THREAD

**Issue by UncleSamtoshi** [GaloyMoney/galoy-mobile#626]
**Describe the bug**
When an LNURL invoice with an amount is scanned by the BBW app, it is able to read the destination, but the user must manually type in the amount.

**Expected behavior**
When an LNURL QR code is scanned, the amount is auto populated.

**Comment by nicolasburtey** [comment]
duplicated of https://github.com/GaloyMoney/galoy-mobile/issues/660

keeper the other one as it has more comprehensive description
