### ISSUE TITLE
Investigate translations flow

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy-mobile#631]

**Comment by UncleSamtoshi** [comment]
## Background

BBW is a global wallet, and we currently maintain multiple translations of the wallet to varying levels. Right now English and Spanish are the two supported languages, with other languages being contributed through open source. We would like to enable these other languages without hindering the development process. We would also like to provide an easy way for maintaining our Spanish translations as we change the design of the application.

**Current process:** Whenever new translations are added, we request the Spanish translation from the BBW team. We then manually edit all translations files in the galoy-mobile repo using english for any language other than Spanish. For other languages to stay in sync, an open source contributor must come back and submit another pr swapping out the english for the target language.

---
## Exploration of translation management tools


### Phrase Strings vs Transifex
- Customers: Transifex is popular with other bitcoin projects (Bitcoin core, Blue wallet), Phrase is popular with big companies
- Features: Transifex supports crowdsourced translations, Phrase only supports private translation team
- Monthly Price: Transifex $70-100 (potentially free for Open Source), Phrase $36/user
- Usability: Transifex is easier to user with better developer docs

Winner: Transifex

---

## Options Going Forward

#### No Translation management tool
- Workflow:
1. 

#### Transifex with existing localization


#### Transifex with changing localization library

---
## Recommendation
