### ISSUE TITLE
Paying invoices from wallets with private channels (but with routing hints)

### ISSUE THREAD

**Issue by Perlover** [GaloyMoney/galoy-mobile#657]
**Describe the bug**

I tested your wallet and tried to pay an invoice to an SBW wallet. Result - it failed with the reason "No route found". I tried 100 sats or so. I see two possible reasons. Either the wallet is trying to send with a deliberately low commission (I saw 1-2 sats as a fee for 100 sats), or that it does not work correctly with invoices, where there are route hints.I think the second is true.

**To Reproduce**

1. Install [SBW](https://sbw.app/) for Android
2. Create inbound channels in SBW for example (I tried with channels from the [LNBIG](https://lnbig.com/#/open-channel) provider)
3. After the channel was created I made invoice for 100 sats and other invoices.
4. Try to pay invoice from BBW to SBW. Error in BBW is the "No route found".
5. Invoices from SBW can be paid from other SBW wallets or from other wallets.

**Expected behavior**

Invoices with route hints should be paid from BBW (when payee's node not found in LN graph)

**Smartphone (please complete the following information):**

- Device: Galaxy Fold3
- OS: Android 12
- Version v2.0.51 build 352

**Comment by nicolasburtey** [comment]
AFAIK, we don't have those type of issues anymore
