### ISSUE TITLE
Improvement: populate send field with min value from lnurl-pay request

### ISSUE THREAD

**Issue by vindard** [GaloyMoney/galoy-mobile#660]
## Description

With lnurl-pay requests, amounts are expressed as two values: min & max. The sender can choose to send any amount in this range.

For exact requests, the hack lnurl uses is to set the min & max values as the same value. Most wallets can regcognize this and automatically populate the send screen with this value. 

For our wallet we don't do this as yet which adds some UX overhead to a payer scanning an lnurl-pay request. 

### Recommendation

We parse the min/max values from an lnurl-pay request and populate the send field with the min value. A lot of other wallets already do this as well.

---

### Current view when paying lnurl-pay

![image](https://user-images.githubusercontent.com/17693119/199764551-c8baa5f3-1503-442a-ba27-ac57f8e3c9fb.png)

**Comment by nicolasburtey** [comment]
I believe this may have been implemented @vindard. do you have an easy way to reproduce?
