### ISSUE TITLE
app doesn't work with huawei phone

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#67]
related to https://github.com/GaloyMoney/galoy-mobile/issues/4

**Comment by nicolasburtey** [comment]
I think there may be a way to add Google Service manually even if you have an Huawei phone, and so this is one you are seeing?

Otherwise those should be not in firebase because if there is no Google Service then there would be no analytics to my knowledge

I recall that the phone on Huawei otherwise would not sign up properly. but will ask Salim for his inputs

**Comment by nicolasburtey** [comment]
cc @SalimArgueta

**Comment by SalimArgueta** [comment]
Yes there is a way. You need to download the Google play services APK and install manual.

https://www.google.com/url?sa=t&source=web&rct=j&url=https://play.google.com/store/apps/details%3Fid%3Dcom.google.android.gms%26hl%3Des_SV%26gl%3DUS%26referrer%3Dutm_source%253Dgoogle%2526utm_medium%253Dorganic%2526utm_term%253Dgoogle%2Bplay%2Bservices%2Bapk%26pcampaignid%3DAPPU_1_dFrvYOn7AYqv5NoPkeeT-AM&ved=2ahUKEwjphdTvw-PxAhWKF1kFHZHzBD8Q5IQBMAF6BAgDEAQ&usg=AOvVaw2murtBN3oFgEyR3ZMLEvcP

**Comment by nicolasburtey** [comment]
and @SalimArgueta, do you know what is the issue if this is not installed on their phone? They can't log in I think but it seems to be working for @jrbuhl93

**Comment by SalimArgueta** [comment]
I think Google play services open a couple of protocols for work opening different apks. Like Bitcoin Beach. But a couple of Huawei phones don't have it on the factory room.

**Comment by jrbuhl93** [comment]
The apk available at https://ln.bitcoinbeach.com/elzonte has been updated and may offer a better experience for Huawei phones than before. This needs to be verified by people with Huawei phones.
