### ISSUE TITLE
scanning issue with onchain QR code

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#68]
**Describe the bug**
Salim in El Zonte has reported that our QR code doesn't work with many wallets: "trust wallet, binance, okex, strike and wallet of satoshi"

**To Reproduce**
1. Open BitcoinBeach
2. Tap on Receive
3. Show the Onchain QR code (not the lightning invoice showing first)
4. Scan this QR code with other wallet

**Additional context**
Could this be because there is a `bitcoin:` prefix? I think this is supposed to be the standard from a bitcoin perspective. maybe it's unrelated

**Comment by jrbuhl93** [comment]
I tested the strike wallet when testing #74 and the QR codes were working for the strike wallet - with or without his changes to make the QR code uppercase. It also worked when adding an amount or a memo.

**Comment by jrbuhl93** [comment]
Your hunch was right that it is the `bitcoin:` prefix for Binance.
