### ISSUE TITLE
don't ask for pasting clipboard on succesful login

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#680]
This is a new behavior with the most recent version of the iOS (iOS v16.1.1)

iOS is asking whether it's the user want to allow access to keyboard.

Right now this leads to this question during the onboarding, just after pasting the code to login. this is far from ideal. maybe we should only have the paste option in the send menu and no longer check for automatic invoice/lnaddress in the keyboard. 

![IMG_5DD14FBF3E06-1](https://user-images.githubusercontent.com/11156370/205031864-13f12de6-2015-41ef-827d-8b9091e8feb8.jpeg)

**Comment by daviroo** [comment]
We could still use the global clipboard detection but wrap it in code to check if we have the permission first.  Can ask for permission at a more appropriate time e.g. on the send screen.
