### ISSUE TITLE
BIP21 support - default to LN and offer the choice

### ISSUE THREAD

**Issue by openoms** [GaloyMoney/galoy-mobile#681]
BTCPay v1.7.0 introduced BIP21 payment codes eg from: https://signet.demo.btcpayserver.org/apps/2SCdQhwFm464BcHxXn44kRVg3iCr/pos
```
bitcoin:TB1QXL9JKN9NV04SMTNJ3KTTY8ZSCXY9YLFMHET6JP?amount=0.00005824&lightning=LNTBS58240N1P3C3X4TPP5ZXNH9CF84G32GX7JUTP56DZ5E4V4R8GTQ46M2W60URYV8MVEP9DQDRD2PSKJEPQW3HJQ5MFVAHX2APQW3JHXAPQ9P8HYER9WGSYJ3P6YPCX7UEDV9C8QHEJ2DPKG5TGWARX6DPKX3PXXJRCTPHRGDRT2FTXWVMFGDEZJCQZPGXQZURSP5ZKV7LQ4RSDCU280KC67EUSUT66RG233NFGZQAQU8TAC8H7Y76NZS9QYYSSQCL7ACMDQF2CZ5EEMD9M8LDCAFXMKEZ33KJ3G5TUKVF2G5EY7LTSH976GZ7DJYXXTUR9DYE5YKT6QV0PRDE5N4LCK8GDFVLD5ERU9WSQQKS3RMP
```

When scanning the BIP21 payment link QR BBW defaults to the onchain address offered and there is no option to pay on LN.

I think the default should be LN, but the best would be to be able to offer the choice between paying on LN and onchain if both are offered.

Update: the new Zeus v0.7.0 release candidate also offers to show BIP21/unifiedQRcode links: https://github.com/ZeusLN/zeus/releases

**Comment by agbegin** [comment]
Is this the same issue @sbddesign flagged with this issue? 
https://github.com/GaloyMoney/galoy-mobile/issues/411

If it's a good bounty candidate I can publish one, lmk.

**Comment by openoms** [comment]
> Is this the same issue @sbddesign flagged with this? #411
> 
> If it's a good bounty candidate I can publish one, lmk.
> 
> PS, a good table of wallet compatibility here https://bitcoinqr.dev/

Correct will paste my notes over there and close this as duplicate. Did not find it with a quick search due to BIP21 vs BIP 21 :)
