### ISSUE TITLE
Paying to certain lightning addresses does not allow inputing a note on the send bitcoin flow

### ISSUE THREAD

**Issue by daviroo** [GaloyMoney/galoy-mobile#685]
If you try and send some sats to davidborthwick@coincorner.io using BBW it's impossible to enter any text in the note field.  Not sure if this is a general issue when paying to any lightning address or if it's being caused by the lnurl response from coincorner but worth looking into.

**Comment by nicolasburtey** [comment]
just did a test and this sounds to be working now
