### ISSUE TITLE
Optimise display for phone numbers when signing up

### ISSUE THREAD

**Issue by Extheoisah** [GaloyMoney/galoy-mobile#700]
the app currently shows by default, El Salvadorian phone ZIP code regardless of the region/country you're based. This should be dynamic so as to reflect the country you are based. e.g. Nigerian users onboarding to the app should see the Nigerian flag and the phone code (+234) in the Sign Up screen

**Comment by isaack-njama** [comment]
I'd like to work on this @Extheoisah

**Comment by nicolasburtey** [comment]
this has been done
