### ISSUE TITLE
Misalignment of finished section button on earn quiz

### ISSUE THREAD

**Issue by cryptosalomao** [GaloyMoney/galoy-mobile#71]
**Expected behavior**
The button text must be centered

**Screenshots**
![image](https://user-images.githubusercontent.com/15071063/124486855-667fb880-dd84-11eb-953b-022b6d9be436.png)

**Comment by nicolasburtey** [comment]
I think it's an issue specific to Android.

**Comment by MikeMwambia-TrojanSystem** [comment]
Can't reproduce on ios
![notReproduced](https://user-images.githubusercontent.com/5917824/129897872-a6fe6763-a058-41ce-adc3-0738c3c983a6.jpeg)

**Comment by secondl1ght** [comment]
I put in a PR to fix this #405

**Comment by nicolasburtey** [comment]
Thanks @secondl1ght
