### ISSUE TITLE
Add "send max." button to send screen

### ISSUE THREAD

**Issue by cryptosalomao** [GaloyMoney/galoy-mobile#73]
**Describe the solution you'd like**
When sending some sats, it would be good to have a "send max." button to send all the available balance. It's useful when doing checkout

**Suggestion**:
Put it on the left side of the amount input component
![image](https://user-images.githubusercontent.com/15071063/124505775-9c329a80-dda0-11eb-90b9-a58d975f00e1.png)

**Comment by nicolasburtey** [comment]
related to https://github.com/GaloyMoney/galoy/pull/275

**Comment by nicolasburtey** [comment]
also related to https://github.com/GaloyMoney/galoy/issues/16

**Comment by rimbener** [comment]
@samerbuna, @daviroo What do you think about using a button under the input, like this:

![Screen Shot 2021-11-08 at 19 07 01](https://user-images.githubusercontent.com/22820029/140825826-6c1670a7-fdce-4326-87d9-f636baa8c132.png)

**Comment by rimbener** [comment]
@samerbuna, @daviroo What do you think about using a button under the input, like this:

![Uploading Screen Shot 2021-11-08 at 19.09.54.png…]()

**Comment by rimbener** [comment]
@samerbuna, @daviroo What do you think about using a button under the input, like this:

![Screen Shot 2021-11-08 at 19 09 54](https://user-images.githubusercontent.com/22820029/140826204-a9f4ccc2-b3fe-4391-9bc7-6a7505fb1288.png)

**Comment by nicolasburtey** [comment]
not a huge fan on my side. blue wallet has done it in a way where it's show on the upper part of the keyboard when the keyboard is being displayed AFAIR. it's less obvious where to find it but because it's not an option that is very frequently used I think that's ok

**Comment by nicolasburtey** [comment]
duplicated of #862
