### ISSUE TITLE
THE APP IS LOGOUT USERS. THEN THE APP IS CLOSING AUTOMATICALLY AND LOGOUT THE USER AGAIN. 

Reported 5 ESA 1 Guatemala 



### ISSUE THREAD

**Issue by SalimArguetaSV** [GaloyMoney/galoy-mobile#786]
![IMG-20230103-WA0012.jpg](https://user-images.githubusercontent.com/105733968/210480234-988ea82a-df35-4a28-901a-38ebd34f008b.jpg)![IMG-20230103-WA0014.jpg](https://user-images.githubusercontent.com/105733968/210480493-b35ec6e8-564e-4a2b-9b27-1666eb018bf3.jpg)

**Comment by nicolasburtey** [comment]
this should have been fixed
