### ISSUE TITLE
App doesn't read clipboard for invoice, LNURL or on-chain address

### ISSUE THREAD

**Issue by pretyflaco** [GaloyMoney/galoy-mobile#800]
**Describe the bug**
App doesn't read clipboard for invoice, LNURL or on-chain address

**To Reproduce**

1. Copy a LN invoice to your mobile's clipboard
2. Open BBW app

**Expected behavior**
BBW app should check clipboard and suggest to pay invoice, LNURL or on-chain address

**Additional context**
This used to work until recently.

**Comment by openoms** [comment]
Just showing the new start screen of Zeus v0.7+.
I really like how there is a dedicated button for the clipboard
![image](https://user-images.githubusercontent.com/43343391/211145807-4fe946cf-59cf-400e-9e90-629a2c2eea08.png)


Going to `Send` doesn't autofill only when pressing the button (good to be in control):
![image](https://user-images.githubusercontent.com/43343391/211145850-d0be0e6a-c1c8-41f9-bead-a1bd3e3fc4c2.png)

When clicking the clipboard icon or the `Paste from clipboard` it goes straight to the decode view:
![image](https://user-images.githubusercontent.com/43343391/211145898-c0d5a294-8c7f-48d2-974e-05d88b2c958b.png)
They made a good job with this one.

**Comment by nicolasburtey** [comment]
> **Describe the bug** App doesn't read clipboard for invoice, LNURL or on-chain address
> 
> **To Reproduce**
> 
> 1. Copy a LN invoice to your mobile's clipboard
> 2. Open BBW app
> 
> **Expected behavior** BBW app should check clipboard and suggest to pay invoice, LNURL or on-chain address
> 
> **Additional context** This used to work until recently.

so closing this one because this is an intentional behavior given the fact iOS now open a popup when an app is trying to read the clipboard so automatic clipboard reading is now generally discouraged.
