### ISSUE TITLE
spend all / empty wallet on "Send Bitcoin" process

### ISSUE THREAD

**Issue by vv01f** [GaloyMoney/galoy-mobile#862]
A user, e.g. merchant that accepts bitcoin, wants to empty their ln sats onchan to the savings wallet…
but the fee estimation and  amount to determination of the amount and fees is not easy to guess.

Give the an easy way to correct the amount and fulfill the fee requirements. Either to empty the wallet or lower the amount in favor of the fees.

If any of this already is in place I was unable to see it and maybe it can be made more obvious. 
There might be other reasons for the payment being blocked I assumed in #861

**Comment by nicolasburtey** [comment]
closing this one. this has been implemented.
