### ISSUE TITLE
show username/BBW address in settings

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#873]
probably below phone.

**Comment by Ayush0054** [comment]
hi can i take this issue

**Comment by nicolasburtey** [comment]
> hi can i take this issue

let me know if you have any questions on this. I would start by making sure storybook works, and work with storybook on this.

**Comment by Ayush0054** [comment]
![image](https://user-images.githubusercontent.com/97244608/219442735-34f3cf83-7983-4e3f-926b-e8c28c2ce55c.png)

feedback please

**Comment by nicolasburtey** [comment]
Looks good to me. How would it look like when it's not authed?

**Comment by nicolasburtey** [comment]
Feel free to post a PR if you want feedback on the code

**Comment by Ayush0054** [comment]
![image](https://user-images.githubusercontent.com/97244608/219665479-5271a02f-5136-47f2-823c-294580311b4c.png)
![image](https://user-images.githubusercontent.com/97244608/219665514-b53abb55-863b-40bd-b9d1-18b553f82d14.png)

auth disabled
![image](https://user-images.githubusercontent.com/97244608/219665751-54ac2afb-2bb4-4e49-b023-4857f8ff7771.png)
![image](https://user-images.githubusercontent.com/97244608/219665885-e82b6c2c-367e-4db5-a830-18b28ee640ed.png)

**Comment by Ayush0054** [comment]
![image](https://user-images.githubusercontent.com/97244608/219666289-d249c1bd-a965-493d-b22d-2a10f1405a7c.png)
![image](https://user-images.githubusercontent.com/97244608/219666351-56831d2c-7e8d-4a76-a9e8-ff17513534f8.png)
when not authed
![image](https://user-images.githubusercontent.com/97244608/219666421-91a58e17-18ce-4e59-b248-66c4a0da8bd0.png)
![image](https://user-images.githubusercontent.com/97244608/219666469-372a5a20-4619-42ef-9806-bf327683532d.png)

**Comment by Ayush0054** [comment]
@nicolasburtey  do i need to remove changes like in eslint  , i18n files (due to yarn update-translation) while making pr
