### ISSUE TITLE
givee more context to the To: field in send Bitcoin Screen

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#90]
I received screenshots for support when people have some issues, and often this is screenshots from the send screen. It's hard to know if the issues arises related to a bitcoin address or an lightning invoice because the To: field will crop the content. 

Which made me think that we should have a way to highlight, after the To field has been set, if this is a lightning invoice, an onchain address, or a username. This would be useful for the (new) users and also for us on the support side. 

Not sure how we could do that yet from a design standpoint but something to consider. Maybe the bitcoin design team would have some insights.

**Comment by jrbuhl93** [comment]
I noticed this comment in the design-review channel for Bitcoin design that is related.

![Screenshot from 2021-07-15 07-16-21](https://user-images.githubusercontent.com/35902932/125786546-6db207d8-9893-4f02-9647-87a05943dbe3.png)

One way to do this on the same screen is to add an icon or message that indicates the payment type we have parsed. Another is to split the payment process into multiple screens.
