### ISSUE TITLE
Update German translation in mobile app

### ISSUE THREAD

**Issue by pretyflaco** [GaloyMoney/galoy-mobile#983]
German translation is now 100% complete. 
https://www.transifex.com/galoy/bitcoin-beach-wallet/language/de/

**Comment by nicolasburtey** [comment]
I don't think there is a need to create ticket @pretyflaco. you can probably push a PR directly from transifex instead?

**Comment by nicolasburtey** [comment]
only adding a new language that doesn't already exist need dev intervention
